### ISSUE TITLE
Problema Plugin Shopify > Mercado Pago

### ISSUE THREAD

**Issue by gustavopalencia** [mercadopago/devsite-docs#1023]
Existe um problema quando você tem a configuração no mercado pago ativada para recuperar venda e o cliente executa via PIX para recebimento. Sei que já temos a recuperação do carinho no shopify mas se caso a loja mantenha ativo também no mercado pago existe uma falha na sincronia onde o carrinho se mantém abandonado no shopify.

**Comment by MercadoPagoDevelopers** [comment]
Olá @gustavopalencia 

Para poder te ajudar com sua dúvida, por favor nos contate pelo nosso  [canal de suporte](https://www.mercadopago.com.br/developers/pt/support/) para que possamos te responder o quanto antes.

Atenciosamente,
**Equipe de suporte a desenvolvedores de Mercado Pago**
