### ISSUE TITLE
no se puede acceder a la app

### ISSUE THREAD

**Issue by Estefycp** [mercadopago/devsite-docs#1034]
no se puede acceder a la app de mercadopago, ni con contraseña ni con codigo

**Comment by MercadoPagoDevelopers** [comment]
Hola @Estefycp ,

Te pedimos disculpas por la demora en responder. Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support) para que podamos responderte cuantos antes.

Saludos, 
**El equipo de soporte a desarrolladores de Mercado Pago**
