### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by santii2020** [mercadopago/devsite-docs#1071]
Tendrían que hacer una actualización de la aplicación, así con AUTORIZACIÓN de los padres los mayores de 13 años puedan utilizar la aplicación, que se le solicite verificación al padre para hacer compras, etc. Ya que, hoy en día los adolescentes también puedan utilizar esta aplicación para hacer pagos con QR. Gracias.

**Comment by kuchmanski** [comment]
PIX é gerado com a informação incorreta no checkout através da API e não é possível efetuar o pagamento. A chave PIX está sendo gerada com informaçãoes misturadas com os dados do usuário e a tornam inválidas para pagamento. Em vários sites que geram chaves PIX pelo Mercado Pago estão sendo geradas chaves inválidas.

**Comment by MercadoPagoDevelopers** [comment]
Hola,

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/contact) para que podamos responderte cuantos antes.

Pronto Mercado Pago tendrá novedades al respecto.

Saludos, 

**El equipo de soporte a desarrolladores de Mercado Pago**
