### ISSUE TITLE
No funciona auto_return en mi preference

### ISSUE THREAD

**Issue by diegodyd** [mercadopago/devsite-docs#1081]
## Context
Ya integre el Checkout Pro en mi sistema. Pero tengo el drama de que necesito automatizar el redireccionamiento al final para asegurarme de que el pago se registra en el sistema y no solo en Mercado Pago. Porque si lo dejo manual, me arriesgo a que cierren la ventana sin apretar el boton de "Volver al sitio". 

### Description
Aca esta el codigo PHP donde hago mi preference, tengo configurado el auto_return, pero no funciona, ni con "Approved" ni con "All". Simplemente se efectua el pago y no pasa nada si no haces clic en el boton. Solo probe utilizando usuarios y credenciales de prueba, sera por eso?

`// SDK de Mercado Pago
    require 'mercadopago/autoload.php';

    // Agrega credenciales
    MercadoPago\SDK::setAccessToken($mp['access_token']);

    // Crea un objeto de preferencia
    $preference = new MercadoPago\Preference();

    // Crea un ítem en la preferencia
    $item = new MercadoPago\Item();
    $item->title = $account['accountname'];
    $item->quantity = 1;
    $item->unit_price = $_REQUEST['pago'];

    $preference->items = array($item);    
    
    //Datos del cliente
    $id = array();
    if(strpos($account['siccode'], '-') === false){
        $id['type'] = "DNI";
    }else{
        $id['type'] = "CUIT";
    }    
    $id['number'] = $account['siccode'];
    $payer = new MercadoPago\Payer();
    $payer->name = $account['accountname'];        
    $payer->identification = $id;
    
    $preference->payer = $payer;        
    $preference->auto_return = "all";
    
    //A donde se re dirige el wizard de MP cuando terminas de configurar el pago, salga bien, salga mal o quede pendiente el pago, respectivamente.
    $preference->back_urls = array(
        "success" => "http://localhost/SistemaGestion/pagarMP.php?success=true&accountid=".$_SESSION['accountid']."&pagado=".$_REQUEST['pago'],
        "failure" => "http://localhost/SistemaGestion/pagarMP.php?failure=true",
        "pending" => "http://localhost/SistemaGestion/pagarMP.php?pending=true"
    );    
    
    //Metodos de pago excluidos, en este caso las opciones de pagar en efectivo x algun medio como RapiPago
    $preference->payment_methods = array(
        "excluded_payment_types" => array(  
                                        array("id"=>"ticket"), 
                                        array("id"=>"bank_transfer"), 
                                        array("id"=>"atm")
                                    )
    );
    //Con esto le digo que solo se pueden aceptar pagos aprobados o rechazados, nada de pendientes.
    $preference->binary_mode = true;    
    //Aca guardo el ID del cliente para saber quien pago.
//    $preference->additional_info = $_SESSION['accountid'];    
    //Nombre que figurara en el resumen de tarjeta del cliente.
    $preference->statement_descriptor = "Sistema de administracion";
    $preference->save();`

Repito, funciona todo perfectamente, excepto el redireccionamiento automatico.

**Comment by diegodyd** [comment]
Ya lo solucione, tenia el wizard configurado en modo "Modal".

**Comment by LuuchoRocha** [comment]
@dydsoft buen día,  podrías brindarme más detalles sobre cómo lo solucionaste por favor?
Tengo el mismo problema y no lo puedo solucionar.  En el lado del cliente en el js tenias "modal"? yo estoy redireccionando a init_point y en ningún lado le seteo el mode al wizard.
Te agradecería mucho si compartieras el código del lado del cliente.  
Saludos
