### ISSUE TITLE
PIX é gerado com erro no API de checkout Mercado Pago, as chaves geradas são inválidas

### ISSUE THREAD

**Issue by kuchmanski** [mercadopago/devsite-docs#1102]
## Context
Include:
- Articles and sections involved (with links).
- Screenshots to serve as examples.

### Description
Write a brief summary of the problem or error found. Include all information you consider relevant: where it appears, when does the situation happens and if you have any suggestions on how to solve it.

**Comment by kuchmanski** [comment]
PIX é gerado com a informação incorreta no checkout através da API e não é possível efetuar o pagamento. 
A chave PIX está sendo gerada com dados misturada com outras informações do usuário e a tornam inválidas para pagamento.
Em vários sites que geram chaves PIX pelo API de checkout Mercado Pago estão sendo geradas chaves com erro.

**Comment by kuchmanski** [comment]
https://user-images.githubusercontent.com/63468982/113042389-84c88d80-9171-11eb-9380-336b71c70530.png

**PIX deve ser gerado somente com 32 caracteres (letras e números).** 
**O Mercado Pago está gerando chave PIX com 141 caracteres!**

**Comment by Maycomsantos** [comment]
para mantener el estándar, escriba en inglés o español para mejorar para que otros colaboren

**Comment by kuchmanski** [comment]
> para mantener el estándar, escriba en inglés o español para mejorar para que otros colaboren

Thank You! 
PIX is generated with the incorrect information at the Woocommerce checkout with the Mercado Pago API.
The PIX key is generated with invalid data for payment.

**Comment by MercadoPagoDevelopers** [comment]
Olá,

Para poder te ajudar com sua dúvida, por favor nos contate através do nosso [canal de suporte](https://www.mercadopago.com.br/developers/pt/support/contact) para que possamos te responder o quanto antes.

Atenciosamente, 

**Equipe de desenvolvedores do Mercado Pago**
