### ISSUE TITLE
Suscripciones integradas dentro del Plugin 

### ISSUE THREAD

**Issue by lpienia** [mercadopago/devsite-docs#1109]
Cuando van a incorporar nuevamente las posibilidad de cobrar suscripciones a traves del componente para Woocommerce?

Va a ser compatible con https://woocommerce.com/products/woocommerce-subscriptions/?
https://docs.woocommerce.com/document/subscriptions/payment-gateways/?_ga=2.97644694.827006269.1616719459-1646615862.1612451555

Saludos

**Comment by MercadoPagoDevelopers** [comment]
Hola @lpienia ,

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/contact) para que podamos responderte cuantos antes.

Saludos, 

**El equipo de soporte a desarrolladores de Mercado Pago**
