### ISSUE TITLE
Error al confirmar la orden en prestashop

### ISSUE THREAD

**Issue by barbosatrix** [mercadopago/devsite-docs#1112]
La operacion se confirma en mercado pago pero en presashop 1.7.6.5 sale un error al realizar la redireccion y confirmar el pago. El pedido queda creado pero sin pago.

**Comment by MercadoPagoDevelopers** [comment]
Hola @barbosatrix ,

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/contact) para que podamos responderte cuantos antes.

Saludos, 

**El equipo de soporte a desarrolladores de Mercado Pago**
