### ISSUE TITLE
Webhook do PreApproval

### ISSUE THREAD

**Issue by velrino** [mercadopago/devsite-docs#1119]
Estou testando a API de PreApproval e estou tendo algumas dúvidas.

- Por que os pagamentos só estão sendo aprovados 2 ou 3 horas depois de criados e não imediatamente?
- Por que quando faço pagamento só recebo webhook de "Recurring payment validation" ?
- Quando eu tive um pagamento com status "approved" não recebi Webhook

**Comment by MercadoPagoDevelopers** [comment]
Olá @velrino ,

Para poder te ajudar com sua dúvida, por favor nos contate através do nosso [canal de suporte](https://www.mercadopago.com.br/developers/pt/support/contact) para que possamos te responder o quanto antes.

Atenciosamente, 

**Equipe de desenvolvedores do Mercado Pago**
