### ISSUE TITLE
Nueva opción para el modulo prestashop

### ISSUE THREAD

**Issue by TecnoHands** [mercadopago/devsite-docs#1128]
Buenas noches, quería saber si sería posible que agreguen una función al modulo para que el % de comisión cobrado por mercadopago pueda ser cobrado aparte del producto. Ya que si la tienda posee varios métodos de pago, se vuelve una gran complicación, sin contar que es mucho más engorroso para el dueño de la tienda andar sacando cálculos para determinar la rentabilidad del producto. 
Mejor si le facilitan la vida al vendedor ;)
Por ej, un check que habilite la función indicando al comprador le % de recargo aplicado por mercadopago.
Así como también poder mostrar las promociones vigentes de mercadopago con las diferentes tarjetas, dado que estas no son visibles.
Por ej: 3 cuotas con cabal, 2 con hipotecario, etc.
Muchísimas gracias.

**Comment by MercadoPagoDevelopers** [comment]
Hola @TecnoHands ,

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/contact) para que podamos responderte cuantos antes.

Saludos, 

**El equipo de soporte a desarrolladores de Mercado Pago**
