### ISSUE TITLE
Fallo SandBox Prestashop 1.7.7.2

### ISSUE THREAD

**Issue by TecnoHands** [mercadopago/devsite-docs#1129]
Se intento realizar una prueba en sandbox en una tienda prestashop 1.7.7.2 instalada de 0 sin themes ni nada raro.
Al colocar APRO en el nombre del titular de la tarjeta cancela el pedido en el backend de prestashop automáticamente
Y ni siquiera coloca el pedido en cancelado, pero al cliente si le da el estado de aceptado al realizar el pago

![image](https://user-images.githubusercontent.com/16818257/114108706-0de66f80-98aa-11eb-8d66-d2c62e7a01ca.png)
Media pila!!!! Si ni siquiera en Cuarentena y con una pandemia le ponen pilas al modulo como empresa dejan mucho que desear!!!

**Comment by GRIMORIO** [comment]
Hola como van con ese asunto, yo también tengo el mismo problema, he probado de todo hasta actualizar php. y el equipo de soporte de desarrolladores se tomó 5, cinco, días para responder y pedirme de nuevo las capturas de pantalla. mi tienda ya esta en linea y operando de un momento a otro dejo de recibir los pagos.

**Comment by MercadoPagoDevelopers** [comment]
Hola @TecnoHands ,

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/contact) para que podamos responderte cuantos antes.

Saludos, 

**El equipo de soporte a desarrolladores de Mercado Pago**
