### ISSUE TITLE
Novos códigos de erros sem documentação

### ISSUE THREAD

**Issue by juliocesar757** [mercadopago/devsite-docs#1145]
Estava atualizando minha integração para a nova API v2. Começou a aparecer novos códigos de erros como 301, 2062, 3031, 3032, 3033, todos relacionados com dados de cartão de crédito. Não dá pra ficar gerando erros e ficar fazendo a tradução para o português. Gostaria de saber onde encontrar a tabela atualizada com os novos códigos de erros.

**Comment by juliocesar757** [comment]
Translated:
"I was updating my integration to a new API v2. New error codes like 301, 2062, 3031, 3032, 3033 started to appear, all related to credit card data. I would like to know where to find an updated table with the new error codes."

**Comment by MercadoPagoDevelopers** [comment]
Olá @juliocesar757 ,

agradecemos seu contato. Poderia nos enviar o log completo desses erros?
Derivamos sua consulta a equipe responsável para que a revise e corrija o quanto antes.

Atenciosamente, 

**Equipe de desenvolvedores do Mercado Pago**

**Comment by juliocesar757** [comment]
Estou solicitando informações completas do códigos de erros gerados pela API já que na documentação não tem os códigos informados. Não entendo porque solicitar o log de erros.

**Comment by MercadoPagoDevelopers** [comment]
Olá @juliocesar757 ,

solicitamos os logs apenas como evidência para reportarmos ao time responsável pela correção.

Atenciosamente,

**Equipe de desenvolvedores do Mercado Pago**

**Comment by juliocesar757** [comment]
Na integração abaixo eu coloquei o código de segurança errado de propósito. Daí gera um erro que não está listado no link https://www.mercadopago.com.br/developers/pt/reference/payments/_payments/post

![mp-api-erro](https://user-images.githubusercontent.com/49540652/118285900-4f20ff00-b4a8-11eb-87bc-961489920722.png)

**Comment by biaguerreiromeli** [comment]
Olá, @juliocesar757! 

Pedimos nossas mais sinceras desculpas pelo inconveniente no tempo de resposta e informamos que o seu feedback está sendo analisado com atenção pela equipe do Mercado Pago para resolvermos este problema o mais rápido possível. 

Muito obrigada pela compreensão!

**Comment by biaguerreiromeli** [comment]
Oi, @juliocesar757 ! 

Pedimos desculpas pela demora e pelo inconveniente no seu fluxo de trabalho.

Mesmo sendo aberto, este espaço não pretende ser uma ferramenta de suporte a problemáticas inerentes à plataforma e suas integrações. Ele serve apenas para armazenar código e documentações públicos.

**Temos um canal oficial de suporte super preparado para solucionar rapidamente o seu caso.** Por isso, se o erro ainda persiste, compile toda a informação e acesse o link a seguir para compartilhar conosco o problema: https://www.mercadopago.com/developers/pt/support

Muito obrigada pelo seu contato!
