### ISSUE TITLE
Los tipos especificados en la documentación no concuerdan con los solicitados por el SDK (NodeJS)

### ISSUE THREAD

**Issue by jdnichollsc** [mercadopago/devsite-docs#1173]
## Context

Los tipos especificados en la documentación no concuerdan con los solicitados por el [paquete de NodeJS](https://www.npmjs.com/package/mercadopago)
Por ejemplo, https://www.mercadopago.com.co/developers/es/reference/preferences/_checkout_preferences/post
Los atributos de `payer.phone.number` como indica la documentación debe ser String pero la validación exige un `number` como se muestra en el siguiente error:

```
Error: The next fields are failing on validation: ".payer.phone.number": should be number. ".payer.address.street_number": should be integer. ".shipments.receiver_address.street_number": should be integer. ".expiration_date_from": should match pattern "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}-[0-9]{2}:[0-9]{2}$". ".expiration_date_to": should match pattern "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.[0-9]{3}-[0-9]{2}:[0-9]{2}$".
```

### Description
version:`mercadopago: 1.5.7`

Código:
```js
MercadoPago.preferences.create({
  binary_mode: false,
  auto_return: 'approved',
  expires: true,
  expiration_date_from: currentDate.toISOString(),
  expiration_date_to: moment(currentDate).add(3, 'days').toISOString(),
  payment_methods: {
    excluded_payment_methods: [
      { id: 'amex' }
    ],
    excluded_payment_types: [
      { id: 'atm' },
      { id: 'ticket' }
    ],
    installments: 6,
    default_installments: 1
  },
  payer: {
    name: user.firstName,
    surname: user.lastName,
    email: user.email,
    date_created: user.createDate.toISOString(),
    phone: {
      area_code: user.areaCode,
      number: user.phoneNumber
    },
    identification: {
      type: 'CC', // Available ID types at https://api.mercadopago.com/v1/identification_types
      number: user.id
    },
    address: {
      street_name: user.address,
      zip_code: user.postalCode,
      street_number: '1602'
    }
  },
  shipments: {
    receiver_address: {
      zip_code: user.postalCode,
      street_number: '1602',
      street_name: 'Insurgentes Sur',
      floor: '15',
      apartment: '1523',
      city_name: 'Medellin',
      state_name: 'Antioquia'
    }
  }
})
```

Con los mismos datos funciona correctamente creando el POST request desde **Postman**.

![image](https://user-images.githubusercontent.com/2154886/118608357-3aca5400-b77f-11eb-8e12-c295326740ae.png)

Gracias de antemano por su colaboración!

**Comment by jdnichollsc** [comment]
Estos tipos sí son mantenidos por ustedes? https://www.npmjs.com/package/@types/mercadopago

**Comment by biaguerreiromeli** [comment]
Hola @jdnichollsc! 

Te pedimos disculpas por la demora en responder. Gracias por informarnos Y ayudar a mantener nuestra documentación 🚀  Estamos consultando con el equipo responsable y le enviaremos una respuesta lo antes posible.

Saludos,
El equipo de experiencia de desarrolladores de Mercado Pago

**Comment by biaguerreiromeli** [comment]
> Estos tipos sí son mantenidos por ustedes? https://www.npmjs.com/package/@types/mercadopago

De antemano, esta página no es un repositorio de Mercado Pago, por lo que no son tipos validados oficialmente.

**Comment by jdnichollsc** [comment]
> > Estos tipos sí son mantenidos por ustedes? https://www.npmjs.com/package/@types/mercadopago
> 
> De antemano, esta página no es un repositorio de Mercado Pago, por lo que no son tipos validados oficialmente.

Entiendo, es posible que incluyan los tipos desde el repositorio oficial?

**Comment by biaguerreiromeli** [comment]
Hola, @jdnichollsc 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a la problemática inherente a la plataforma y sus integraciones. Solo está destinado a almacenar código y documentaciones públicos.

**Tenemos un canal oficial de soporte súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support

¡Muchas gracias por su contacto!
