### ISSUE TITLE
API de reportes. Developer support está caído.

### ISSUE THREAD

**Issue by jisbruzzi** [mercadopago/devsite-docs#1182]
Buenos días, me contacto por acá porque está caído el soporte para desarrolladores.

No nos funciona la generación de reportes. Gist con el código de pruebas: https://gist.github.com/jisbruzzi/d1c248141add9be5ee57779e893659aa . Generamos suscripciones con dinero real pero no aparece NINGÚN COBRO DE SUSCRIPCIÓN al descargar los reportes por medio de del GET a 'https://api.mercadopago.com/v1/account/settlement_report/'+file_name . Es decir, todos los reportes extraídos vuelven VACÍOS. Les pido por favor me indiquen cómo debo modificar los requests del gist para poder obtener la información.

Noté que la documentación de suscripciones está desactualizada (pueden usar mi gist para actualizar los ejemplos): muchos ejemplos python fallan, y noté que los ejemplos de código en inglés y en español son distintos. Por ejemplo, en inglés las URL dicen "bank_report" y en español dicen "settlement_report".

Muchas gracias,

**Comment by biaguerreiromeli** [comment]
Hola, @jisbruzzi :)

Como ha pasado mucho tiempo desde la solicitud y no hemos tenido notícia más reciente, te pido que vuelvas a intentar el flujo de soporte y / o vuelvas a abrir un problema si el error persiste, ¿de acuerdo?

Buscaremos resolver tu problema lo más rápido posible!

Te pedimos disculpas por las molestias causadas, ya tomamos las medidas necesarias para evitar que algo similar vuelva a ocurrir.

 ¡Muchas gracias por tu contacto!
