### ISSUE TITLE
Error de plataforma con asociacion de usuario

### ISSUE THREAD

**Issue by Lis246** [mercadopago/devsite-docs#1191]
Tengo un grave problema que desde la atención al cliente no pueden resolver porque NO lo entienden y creo que ustedes si por tener acceso a las bases de datos y IDs de usuarios.

Tengo una cuenta en una tienda online (decathlon) con mi correo electrónico. La tienda tiene mercado pago como herramienta de pago. La tienda realizó un reembolso de forma automática a través de mercado pago usando como ID mi correo electrónico, dicho correo electrónico corresponde a una cuenta MUY antigua de mercado libre Venezuela, donde actualmente NO tienen habilitada la opción de mercado pago.

No hay forma de que haga MATCH mi usuario de la tienda online con un usuario válido en mercado pago bajo el mismo correo electrónico.

No me permite acceder a la ayuda y la tienda me indica que debo resolverlo con mercado pago directamente. Pero mercado pago para Venezuela no está habilitado, y esa es la cuenta dominio asociada a mi correo electrónico. Donde se hizo el proceso de reembolso del dinero de forma automática desde la tienda virtual!

AYUDA!!!

**Comment by biaguerreiromeli** [comment]
Hola, @Lis246!

Te pedimos disculpas por la demora y por el inconveniente en tu fluxo de trabajo.

Si el error persiste, recopile toda la información y envíela a nuestro equipo de soporte para resolver el problema: https://www.mercadopago.com.br/developers/en/support.

¡Muchas gracias por tu contacto!
