### ISSUE TITLE
browser.js:49 Missing melidata tracking component - [name:melidata] [level:INFO]

### ISSUE THREAD

**Issue by alemdg** [mercadopago/devsite-docs#1215]
Ejemplo original de https://github.com/mercadopago/checkout-payment-sample/tree/master/client.

No hay frames ni nada por el estilo.

[Report Only] Refused to frame 'https://www.mercadopago.com.ar/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' *.mercadolibre.com".

browser.js:49 Missing melidata tracking component - [name:melidata] [level:INFO]

**Comment by biaguerreiromeli** [comment]
Hola, @alemdg!

Te pedimos disculpas por la demora y por el inconveniente en tu fluxo de trabajo.

Si el error persiste, recopile toda la información y envíela a nuestro equipo de soporte para resolver el problema: https://www.mercadopago.com.br/developers/en/support.

¡Muchas gracias por tu contacto!
