### ISSUE TITLE
Integração com Rails 6

### ISSUE THREAD

**Issue by cabanga** [mercadopago/devsite-docs#1222]
Olá estou a fazer integração do mercado pago em aplicações rails com a versão 6 e ruby 3.
Simples mente tem erro de inicialização

![image](https://user-images.githubusercontent.com/10489611/126031466-3a00fd1b-4d86-4058-8294-787e211b9202.png)

E mesmo alterando a class de Mercadopago para MercadoPago ainda continua a dar erro
Voces têm alguma solução para isso.

A solução possivel seria a reinicialização do servidor como indica este metodo
https://stackoverflow.com/questions/50053497/uninitialized-constant-mercadopagosdk

Mas não funciona

**Comment by biaguerreiromeli** [comment]
Hola, @cabanga!

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Si el error persiste, recopile toda la información y envíela a nuestro equipo de soporte para resolver el problema: https://www.mercadopago.com.br/developers/en/support.

¡Muchas gracias por tu contacto!
