### ISSUE TITLE
Error al tratar de hacer login wp 5.7.2

### ISSUE THREAD

**Issue by gerlandog** [mercadopago/devsite-docs#1236]
![Screenshot_20210728-153502](https://user-images.githubusercontent.com/21976353/127379958-f1c4e9f5-9943-4c6c-b056-c08014345d4f.png)

**Comment by biaguerreiromeli** [comment]
Hola, @gerlandog!

Te pedimos disculpas por la demora y por el inconveniente en tu fluxo de trabajo.

Si el error persiste, recopile toda la información y envíela a nuestro equipo de soporte para resolver el problema: https://www.mercadopago.com.br/developers/en/support.

¡Muchas gracias por tu contacto!
