### ISSUE TITLE
[sdk-js 2.0] - Problem creating a card token using an already saved card

### ISSUE THREAD

**Issue by tomfloresa** [mercadopago/devsite-docs#1240]
## Description

When trying to generate a `card token` using the `cardId` from a saved card and it's CVV, the script throws an error. 

Consider the following snippet from [this documentation](https://www.mercadopago.cl/developers/es/guides/online-payments/checkout-api/v2/advanced-integration):

``` javascript
(async function createToken() {
       try {
           const token = await mp.createCardToken({
               cardId: document.getElementById('cardId').value,
               securityCode: document.getElementById('cvv').value,
           })

            // Use the received token to make a POST request to your backend
           console.log('token received: ', token.id)
       }catch(e) {
           console.error('error creating token: ', e)
       }
   })()
```
As per stated above, for a registered card is only necessary to pass the `cardId` and the `securityCode`. In contrast, when checking the [github documentation for the SDK](https://github.com/mercadopago/sdk-js/#mp-instancecreatecardtokencardtokenparams), all the fields of the `cardParamsObject` are **always mandatory**, which is contradictory.

When executing the `createCardToken`, it throws `TypeError: Cannot read property 'replace' of undefined`. This is because the `createCardToken` is actually expecting an object with, at least, a field with the name `cardNumber`. The following is an extract of the script available through `<script src="https://sdk.mercadopago.com/js/v2"></script>`

``` javascript
        async createCardToken(e, t) {
            const {cardNumber: n} = e
              , i = E(n)
              , o = w({
                methodName: "createCardToken",
                incomingParams: {
                    ...e,
                    cardNumber: i
                },
                validateFieldsParams: t
            });
```
`cardNumber` is not present on the response when retrieving registered cards. The most similar is `card_number_id`, but is not working as expected when using it as the value for `cardNumber`. Furthermore, it doesn't make much sense to ask for the card number when leveraging the registered cards feature.

## SDK Version
V2

## Steps To Reproduce

1. Create a MercadoPago instance
2. Call the `createCardToken` method passing an object only with the `cardId` and `securityCode` keys (as seen on documentation).
3. Expect the call to return `TypeError: Cannot read property 'replace' of undefined`

## Expected Results

When executing the `createCardToken`method, an object with a field `id`containing a valid token should be returned.

**Comment by biaguerreiromeli** [comment]
Hola @NicholasPedroso, 

te pedimos disculpas por la demora. Como puedes ver en el [PR #44](https://github.com/mercadolibre/fury_openplatform-sdk-javascript-v2/pull/44), ya solucionamos el problema y puedes seguir en fluxo como esperado. 

Muchas gracias por tu contacto,

el equipo de Mercado Pago.
