### ISSUE TITLE
Error al redireccionar en pse

### ISSUE THREAD

**Issue by rouderz** [mercadopago/devsite-docs#1246]
Me encuentro teniendo un problema al generar un pago con el metodo de pse, al momento de que el pago fue realizado con exito y espero los 10 segudos para ser redireccionado a mi sitio web, nunca se me envian los parametros por la url y en el caso, me envia a el dashboard principal de la misma, he definido mis back url en mi codigo mas no son tomadas en cuenta en ese metodo de pago, quisiera saber si es un problema o es que hay reglamentariamente generar un ipn para el mismo?

tambien quiero acotar que el auto_return no esta funcionando.

```JS
 const preferences = {
        items: event.body.items,
        payer: event.body.payer,
        back_urls: {
          "success": "https://uricom/web/dashboard/congratulations",
          "failure": "https://uri.com/web/dashboard/marketplace",
          "pending": "https://uri.com/web/dashboard/congratulations"
        },
        marketplace_fee: fee,
        external_reference: event.body.id,
        auto_return: "approved",
      }
```

**Comment by biaguerreiromeli** [comment]
Hola, @rouderz!

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Si el error persiste, recopile toda la información y envíela a nuestro equipo de soporte para resolvermos el problema: https://www.mercadopago.com.br/developers/en/support.

¡Muchas gracias por su contacto!

**Comment by LuuchoRocha** [comment]
El error persiste y en el centro de atención no responden nunca... tickets abiertos durante días y días.  
Imposible hacer funcionar las back_urls
