### ISSUE TITLE
Cartão de teste mastercard invalido

### ISSUE THREAD

**Issue by mauroagr** [mercadopago/devsite-docs#1248]
A verificar o numero de cartão de teste do mastercard, é invalido em vários lugares que testei, 5031 4332 1540 6351
A princípio cartões mastercard nao começam com 50....mas 51...55...
 
## Context
Include:
https://github.com/mercadopago/devsite-docs/blob/development/guides/online-payments/checkout-api/testing.pt.md
https://www.getbincodes.com/bin-checker/?keywords=503143

### Description
Codigo BIN dos cartoes de teste do mastercard estão invalidos

**Comment by biaguerreiromeli** [comment]
Olá, @mauroagr ! Tudo bem com você? 

Obrigada pelo seu feedback! Ele é valioso para a construção da nossa documentação 🚀  

Validei aqui a sequência numérica do cartão teste Mastercard (MLB) e está tudo certo com ela, funcionou perfeitamente. 

Antes de tentar mais uma vez do seu lado, confira se os passos abaixo foram realizados antes da validação:

- Criar uma preferência de pagamento;
- Usar o Checkout Pro;
- Seguir corretamente todas as instruções para completar o fluxo de pagamento;
- Usar o e-mail de um usuário teste para concluir a compra.

Caso o erro persista, peço que envie mais detalhes do fluxo, como screenshots da operação, para o nosso time de suporte: https://www.mercadopago.com.br/developers/pt/support
