### ISSUE TITLE
 merchant_order status does not change in test environment

### ISSUE THREAD

**Issue by robsondrs** [mercadopago/devsite-docs#1259]
when finalizing a purchase the merchant order did not change its status, it remained always as "openned", making the tests difficult. in test environment
For example, when consulting the API https://api.mercadopago.com/merchant_orders/3105434525 the result for status is always "opened"

**Comment by maumarteau** [comment]
Hi, I have the same problem, have you found a solution?

**Comment by biaguerreiromeli** [comment]
Hola, @robsondrs 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a la problemática inherente a la plataforma y sus integraciones. Solo está destinado a almacenar código y documentaciones públicos.

**Tenemos un canal oficial de soporte súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support

¡Muchas gracias por su contacto!
