### ISSUE TITLE
Unable to process binding "mageInit"  en checkout personalizado del módulo para magento (2.4)

### ISSUE THREAD

**Issue by leojdiaz83** [mercadopago/devsite-docs#1279]
Al activar el checkou personalizado en magento 2.4  nos econtramos con el siguiente error . 

Uncaught TypeError: Unable to process binding "mageInit: function(){return {'transparent':{'context':context(),'controller':getControllerName(),'gateway':getCode(),'orderSaveUrl':getPlaceOrderUrl(),'cgiUrl':getCgiUrl(),'dateDelim':getDateDelim(),'cardFieldsMap':getCardFieldsMap(),'nativeAction':getSaveOrderUrl()},'validation':[]} }"
Message: Cannot read property 'controllerName' of undefined

**Comment by biaguerreiromeli** [comment]
Hola, @leojdiaz83 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a la problemática inherente a la plataforma y sus integraciones. Solo está destinado a almacenar código y documentaciones públicos.

**Tenemos un canal oficial de soporte súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support

¡Muchas gracias por su contacto!
