### ISSUE TITLE
[Prestashop] URL de términos de servicio

### ISSUE THREAD

**Issue by neoacevedo** [mercadopago/devsite-docs#1283]
Sería posible que se pudiera personalizar la URL de los términos de servicio?

Digamos, que los términos de servicio los tenga en una URL completamente diferente. En el módulo GDPR de Prestashop está la opción de modificar incluso el texto que se muestra. Sería posible algo también para el módulo de Mercado Pago?

**Comment by biaguerreiromeli** [comment]
Hola, @neoacevedo 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a preguntas o errores inesperados de la plataforma y sus integraciones.

**Tenemos un canal oficial súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
