### ISSUE TITLE
Solução melhor de segurança do que  lei brasileira que ira dar limite de 1000 reais ao pix 

### ISSUE THREAD

**Issue by arthu7r7** [mercadopago/devsite-docs#1286]
Após a onda de sequestros em São Paulo nos quais os bandidos/sequestradores obrigam as vítimas a fazer pix para contas terceiras administradas por criminosos,( o criminoso pode pegar um morador de rua que tem documentos e fazer uma conta no nome desse morador de rua sem mais problemas por exemplo) . 

Já há iniciativas legislativas para que aja o regulamento e limites para pix em 1000 reais por noite, algo nocivo para economia e para a vida das pessoas que utilizam o serviço, uma vez que não enxergam a solução no mercado, burocratas se apressam para regular a movimentação do dinheiro com a ideia de assegurar os usuários de maiores prejuízos.

Minha ideia é a segurança fornecida por questões pessoais que a pessoa deverá responder após entrar no aplicativo do seu banco e selecionar a opção pix, exemplo: duas questões alternativas com quatro opções de resposta criadas pelo próprio usuário ,cada uma com tempo de 5 segundos para responder, caso não seja respondida ou selecionada o opção errada, será despertado um alerta para a central do mercado pago que a atividade suspeita no dispositivo do usuário ,o usuário poderá selecionar os horários em que se haver atividade suspeita em sua conta, a central poderá alertar as autoridades a enviar viaturas ao local da atividade suspeita do dispositivo, uma vez que só será permitido o uso do pix com a localização gps do dispositivo ligada, algo que pode ser opção de segurança do usuário, assim como a verificação em duas etapas já existente.

**Comment by biaguerreiromeli** [comment]
oi, @arthu7r7 👋 

Oi, @tangzin :wave: 

Mesmo sendo aberto, este espaço não pretende ser uma ferramenta de suporte a feedbacks e erros inesperados da plataforma e suas integrações.

Mas não se preocupe! Você pode compartilhar a sua ideia com o nosso time de suporte:  https://www.mercadopago.com/developers/pt/support/center/contact

Muito obrigada pelo seu contato!
