### ISSUE TITLE
Documentacion de Refund (Partial / Complete)

### ISSUE THREAD

**Issue by betoxd40** [mercadopago/devsite-docs#1294]
## Context

No encuentro documentacion sobre aplicar refund en los payments, la unica documentacion que pude encontrar via SDK es la siguiente: 

- https://www.mercadopago.com.ar/developers/es/guides/manage-account/account/cancellations-and-refunds
- Revisando este repositorio, encontre una pagina oculta que habla sobre como aplicar refund via API: https://www.mercadopago.com.ar/developers/es/guides/resources/localization/migrating-v0-v1

Luego de haber creado un pago exitoso, y con suficiente dinero en la cuenta para aplicar una devolucion, he intentado mil maneras para poder devolver el dinero, ya sea via SDK, via API.

Ejemplos:

GET / POST -> https://api.mercadopago.com/v1/payments/payment_id/refunds

mercadopago.payment.refund(payment_id)

En cualquiera de los casos, obtengo la siguiente respuesta:

```
{
  "message": "Payment not found",
  "error": "not_found",
  "status": 404,
  "cause": [
    {
      "code": 2000,
      "description": "Payment not found",
      "data": "03-09-2021T12:13:10UTC;5af23d14-1cb6-4b98-9ed7-648cea285cab"
    }
  ]
}
```

Lo cual me lleva a pensar que actualmente el endpoint no esta disponible, o algun issue esta pasando. 

Cabe destacar que el payment existe y esta aprovado, si llamo a https://api.mercadopago.com/v1/payments/payment_id, me devuelve la informacion correcta.

**Comment by biaguerreiromeli** [comment]
Hola, @betoxd40 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a errores inesperados de la plataforma y sus integraciones.

**Tenemos un canal oficial súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
