### ISSUE TITLE
Translation Missing on Marketplace

### ISSUE THREAD

**Issue by ignacioricci** [mercadopago/devsite-docs#130]
![screen shot 2018-05-18 at 2 39 58 pm](https://user-images.githubusercontent.com/611708/40249469-7e384c46-5aa9-11e8-868a-31c8330835e9.png)

**Comment by joelibaceta** [comment]
Solved in https://github.com/mercadolibre/fury_devsite/commit/b2af372bfd81bb48faef573f9f15021704485367
