### ISSUE TITLE
Marketplace api feature request

### ISSUE THREAD

**Issue by nicosefer** [mercadopago/devsite-docs#1303]
Seria muy util agregar una feature que permita poder diferir el pago al vendedor e incluso poder incluir varios "vendedores" al modelo tal como lo contempla stripe https://stripe.com/docs/connect/charges-transfers

**Comment by biaguerreiromeli** [comment]
Hola, @nicosefer 👋 

Le pedimos disculpas por la demora de respuesta. 

**Tenemos un canal oficial súper preparado para tu compartir rápidamente tus ideas y feedbacks de la plataforma**: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
