### ISSUE TITLE
auto_return for pix

### ISSUE THREAD

**Issue by member3541** [mercadopago/devsite-docs#1307]
set auto return to pix,

in my app the only payment method without automatic return is the pix

**Comment by biaguerreiromeli** [comment]
Hola, @member3541 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a errores inesperados de la plataforma y sus integraciones.

**Tenemos un canal oficial súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
