### ISSUE TITLE
Falta de documentación para VISA MASTERCARD y pago en cuotas para SANDBOX

### ISSUE THREAD

**Issue by luke92** [mercadopago/devsite-docs#1317]
## Context
- https://www.mercadopago.com.ar/developers/es/guides/online-payments/checkout-pro/test-integration

### Description
Hoy para probar el SANDBOX de VISA Y MERCADOPAGO solo funciona si se usa el banco otro (con issuer_id = 1)
Esto no está explicado en la documentación
![image](https://user-images.githubusercontent.com/1220217/134386163-eaefd9e9-0cc6-417d-9fff-38143eb6b174.png)
En el caso de American Express funciona la tarjeta de prueba con casi todos los bancos

Por lo tanto, al no poder usarse otro tipo de tarjeta, tampoco se puede saber si realmente un cobro que tiene con cuotas sin interes funciona como debería.
![image](https://user-images.githubusercontent.com/1220217/134388595-9ba8d98b-3e09-41ed-b6fb-4fed9ff00ac1.png)

Por otro lado, si probamos enviar un issuer_id que tenga cuotas sin interes con American Express, en la consulta del transactionID figura que se están cobrando las cuotas con interes.

En resumen, creo que falta información en la documentación y por otro lado no se puede ver en SANDBOX como operan las tarjetas de credito que tienen cuotas sin interes

Gracias

**Comment by biaguerreiromeli** [comment]
Hola, @luke92 👋 

¡Muchas gracias por su contacto!
Llevamos los comentarios al equipo responsable de las docs para el fix.

Vamos juntos 🚀
