### ISSUE TITLE
Pagamento Malsucedido

### ISSUE THREAD

**Issue by tangzin** [mercadopago/devsite-docs#1327]
Bom dia!
Estou enfrentando um problema no Mercadopago para Woocommerce e não sei onde recorrer.
Não sei Se é um problema do plugin ou da minha conta no mercadopago. Por não conseguir contato direto com o mercadopago, vim aqui para ver se alguém tem ideia do que pode estar acontecendo.
Vários clientes estão enfrentando problema ao efetuar o pagamento. O pagamento fica como "Aguardando" e depois de aproximadamente 20 minutos, é rejeitado e aparece como "Malsucedido" no painel.

Agradeço desde já.

Att

**Comment by lukidj** [comment]
Ola estou com o mesmo problema, e eles se quer não dar um parecer

**Comment by tangzin** [comment]
> Ola estou com o mesmo problema, e eles se quer não dar um parecer

triste né cara?
não dão o suporte necessário, apenas dizem ser algum erro no cartão do próprio cliente...

**Comment by lukidj** [comment]
chama ae whats 99 991025460

**Comment by garbinmarcelo** [comment]
Olá, conseguiu resolver? Comecei utilizar MP em uma nova loja e no momento estou enfrentando o mesmo problema com pagamentos recusados. Porém até o momento não deram maiores informações.

**Comment by lukidj** [comment]
Salve, acabei que vi que fui banido da plataforma, infelizmente o mercado pago é assim.

So consigo receber pagamentos de boleto ou PIX, ja de cartão não aceita.

**Comment by tangzin** [comment]
> Olá, conseguiu resolver? Comecei utilizar MP em uma nova loja e no momento estou enfrentando o mesmo problema com pagamentos recusados. Porém até o momento não deram maiores informações.

Infelizmente não. Passei a usar a Juno, e mesmo assim alguns pagamentos são bloqueados também. Mas houve uma melhora!

**Comment by garbinmarcelo** [comment]
> Salve, acabei que vi que fui banido da plataforma, infelizmente o mercado pago é assim.
> 
> So consigo receber pagamentos de boleto ou PIX, ja de cartão não aceita.

E deram o motivo que você foi banido?

**Comment by garbinmarcelo** [comment]
> > Olá, conseguiu resolver? Comecei utilizar MP em uma nova loja e no momento estou enfrentando o mesmo problema com pagamentos recusados. Porém até o momento não deram maiores informações.
> 
> Infelizmente não. Passei a usar a Juno, e mesmo assim alguns pagamentos são bloqueados também. Mas houve uma melhora!

Você está usando alguma plataforma? opencart, woocomerce, etc...

**Comment by tangzin** [comment]
> > > Olá, conseguiu resolver? Comecei utilizar MP em uma nova loja e no momento estou enfrentando o mesmo problema com pagamentos recusados. Porém até o momento não deram maiores informações.
> > 
> > 
> > Infelizmente não. Passei a usar a Juno, e mesmo assim alguns pagamentos são bloqueados também. Mas houve uma melhora!
> 
> Você está usando alguma plataforma? opencart, woocomerce, etc...

woocommerce

**Comment by biaguerreiromeli** [comment]
Oi, @tangzin 👋 

Pedimos desculpas pela demora e pelo inconveniente no seu fluxo de trabalho.

Mesmo sendo aberto, este espaço não pretende ser uma ferramenta de suporte a erros inesperados da plataforma e suas integrações.

Temos um canal oficial super preparado para solucionar rapidamente o seu caso.
Por isso, se o erro ainda persiste, compile toda a informação e acesse o link a seguir para compartilhar conosco o problema: https://www.mercadopago.com/developers/pt/support/center/contact

Muito obrigada pelo seu contato!
