### ISSUE TITLE
Checkout Pro: Can't execute test payment

### ISSUE THREAD

**Issue by prfd** [mercadopago/devsite-docs#1328]
Two days ago I was able to make test payments, now it just shows an error message (Ops, an error occurred) with no further details after finalizing the payment using test cards.

**Comment by biaguerreiromeli** [comment]
Hola, @prfd 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a errores inesperados de la plataforma y sus integraciones.

**Tenemos un canal oficial súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
