### ISSUE TITLE
Endpoint for pull MOVEMENTS doesnt exist anymore

### ISSUE THREAD

**Issue by alisonvalente** [mercadopago/devsite-docs#1336]
I have an application that utilizes the endpoint https://api.mercadopago.com/mercadopago_account/movements/search to pull a list of movements.

The problem is that this application stop working two days ago because that endpoint doesnt exist anymore.

There were any changes in the API about the Movements?

I appreciated the attencion.

**Comment by biaguerreiromeli** [comment]
Hola, @alisonvalente 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a preguntas o errores inesperados de la plataforma y sus integraciones.

**Tenemos un canal oficial súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
