### ISSUE TITLE
Error 500 customer card create

### ISSUE THREAD

**Issue by 3fili3** [mercadopago/devsite-docs#1340]
Al querer crear una tarjeta de un cliente, como respuesta me manda status 500 y un mensaje de "Oops! Something went wrong...".

Lo hago de la misma forma que muestra la documentación.

`mercadopago.customers.search(data_serch).then(async respnse => {
  const id: string = respnse.id;
  console.log(id);
  const card_data = {
    "token": "XXXXX_TOKEN_XXXX",
    "customer_id": id,
  }
  mercadopago.customers.cards.create(card_data).then(response => {
    console.log(respnse)
  }).catch(error => {
    console.log(error)
  })
}).catch(error => {
  console.log(error)
});
`
y de igual forma lo intento hacer como viene en la página de mercado libre, pero me sigue arrojando el mismo error.

`mercadopago.customers.search(data_serch).then(async respnse => {
  const id: string = respnse.id;
  console.log(id);
  const card_data = {
    "token": "xxxxxxxxxxxxxx_token_xxxxxxx",
    "customer_id": id,
  }
  try {
    const response =  (await axios({
      url: 'https://api.mercadopago.com/v1/customers/'+id+'/cards',
      method: "POST",
      headers: {Authorization:'Bearer token_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'},
      data: {
        token:"XXXXX_TOKEN_XXXXX"
      }
    })).data;
    console.log(respnse)
  } catch (error) {
    console.log(error);
  }
}).catch(error => {
  console.log(error)
});`

¿Tendrían alguna respuesta para este error ? o sabrían ¿porque me responde con este error?

**Comment by IsabelaBianchi** [comment]
I have the same problem when trying create new customer

**Comment by biaguerreiromeli** [comment]
Hola, @3fili3 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a errores inesperados de la plataforma y sus integraciones.

**Tenemos un canal oficial súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
