### ISSUE TITLE
Não tem documentação de reembolso

### ISSUE THREAD

**Issue by AntonnyAGS** [mercadopago/devsite-docs#1345]
A documentação de reembolso não existe... Fuçando por aí descobri que /payments/${id]/refund nos permite fazer um reembolso.

**Comment by biaguerreiromeli** [comment]
Oi, @AntonnyAGS 👋 

Pedimos desculpas pela demora!

O time do Mercado Pago já está ativamente trabalhando para entregar documentação completa e de qualidade para usuários como você. 

Muito obrigada pelo contato e feedback!
