### ISSUE TITLE
Devoluciones y cancelaciones: Ejemplo inválido

### ISSUE THREAD

**Issue by conceptualben** [mercadopago/devsite-docs#1367]
En la sección "Devoluciones y cancelaciones" (https://www.mercadopago.com.ar/developers/es/guides/manage-account/account/cancellations-and-refunds) el siguiente código de ejemplo no es válido:

```
mercadopago.payment.refund(payment_id)
  .then(function (response) {
    //Procesar respuesta...
  })
  .catch(function (error) {
    //Manejar el error...
  });
```

En la SDK de Javascript no existe mercadopago.payment.refund. Podrán actualizar el ejemplo a algo válido? Es mercadopago.refund.create ?

**Comment by vitorbertolucci** [comment]
In addition to the example not being correct, the `refund` property of `MercadoPago` is typed as `any`, which doesn't help either.

After testing I concluded that the right way to do it using `MercadoPago.refund.create` as you suggested:

```
    const response = await MercadoPago.refund.create({ payment_id: 'PAYMENT_OPERATION_NUMBER' });
```

**Comment by biaguerreiromeli** [comment]
Hola, @conceptualben 👋

¡Muchas gracias por su contacto!
Llevamos los comentarios al equipo responsable de las docs para el fix.

Vamos juntos 🚀
