### ISSUE TITLE
Erros de validação no mp.createCardToken da V2

### ISSUE THREAD

**Issue by lenonfelippi** [mercadopago/devsite-docs#1382]
Ao fazer a migração para a V2 encontrei os seguintes problemas:

1 - Ao tentar criar o token `mp.createCardToken` com informações erradas, não são retornados todos os erros de uma única vez.
![image](https://user-images.githubusercontent.com/65905199/139274823-c1b0da66-8b07-4e02-a9cb-0391e114fd7d.png)
![image](https://user-images.githubusercontent.com/65905199/139274849-69b8f919-2f3c-4009-9b16-04f792e8a3da.png)

2 - Formatos diferentes de mostrar os erros. Seria melhor um padrão:
![image](https://user-images.githubusercontent.com/65905199/139275089-4da95708-e191-4480-bd32-d6bc7d54921d.png)
![image](https://user-images.githubusercontent.com/65905199/139275109-b2604bb2-0c9f-4e38-a0d1-39f2f2dc4020.png)

3 - Utilizo as informações dos cartões de testes do link: https://www.mercadopago.com.br/developers/pt/guides/online-payments/checkout-api/testing#bookmark_cart%C3%B5es_de_teste
O único dado validado dos cartões de testes é o número do cartão.
O Código de segurança aceita qualquer número.
Data de vencimento também aceita qualquer data futura.
![image](https://user-images.githubusercontent.com/65905199/139275821-e9d486f6-f47b-4991-92d5-4c48fa7a60cb.png)

Ao tentar passar o nome do titular do cartão seguindo a tabela de STATUS DE PAGAMENTO que esta na documentação, sempre é finalizado o pagamento, mesmo usando o **OTHE** que deveria ser “**recusado por erro geral**” é aceito.
![image](https://user-images.githubusercontent.com/65905199/139275869-53360e63-df0b-4332-a9a1-9da741c24d86.png)

**Comment by biaguerreiromeli** [comment]
Oi, @lenonfelippi 👋 

Pedimos desculpas pela demora e pelo inconveniente no seu fluxo de trabalho.

Mesmo sendo aberto, este espaço não pretende ser uma ferramenta de suporte a erros inesperados da plataforma e suas integrações.

Temos um canal oficial super preparado para solucionar rapidamente o seu caso.
Por isso, se o erro ainda persiste, compile toda a informação e acesse o link a seguir para compartilhar conosco o problema: https://www.mercadopago.com/developers/pt/support/center/contact

Muito obrigada pelo seu contato!
