### ISSUE TITLE
Alguem sabe como consigo arquivo .P12 do mercado pago, para podermos transformar em arquivo .PEM, esse é o certificado que vai autenticar um pix dinâmico, e também preciso da Url base do mercado pago, sendo que vou usar ele como psp

### ISSUE THREAD

**Issue by kauaicaldas** [mercadopago/devsite-docs#1425]
## Context
Include:
- Articles and sections involved (with links).
- Screenshots to serve as examples.

### Description
Write a brief summary of the problem or error found. Include all information you consider relevant: where it appears, when does the situation happens and if you have any suggestions on how to solve it.

**Comment by biaguerreiromeli** [comment]
Oi, @kauaicaldas 👋 

Pedimos desculpas pela demora e pelo inconveniente no seu fluxo de trabalho.

Mesmo sendo aberto, este espaço não pretende ser uma ferramenta de suporte a erros inesperados da plataforma e suas integrações.

Temos um canal oficial super preparado para solucionar rapidamente o seu caso.
Por isso, se o erro ainda persiste, compile toda a informação e acesse o link a seguir para compartilhar conosco o problema: https://www.mercadopago.com/developers/pt/support/center/contact

Muito obrigada pelo seu contato!
