### ISSUE TITLE
Feature request: different marketplace fee per item (not only per payment)

### ISSUE THREAD

**Issue by cawecoy** [mercadopago/devsite-docs#1427]
Hi, I would love to use your marketplace solution, but it doesn't offer a little thing that is very important for my business model: setting up a different marketplace fee per item. Actually you just allow us to set one marketplace fee for the whole payment (i.e. same marketplace fee for the whole order with multiple items from multiple sellers).

Sometimes our customers need to buy items from different sellers: they put those items in a basket and pay for them through only one payment. The point is that each seller could have different marketplace fees in our marketplace.

As [the Mercado Pago (MP) docs shows](https://github.com/mercadopago/devsite-docs/blob/development/guides/online-payments/marketplace/checkout-pro/create-marketplace.en.md#integrate-the-checkout-pro), this is what anyone could do with MP Marketplace solution:

```
{
    "items": [
        {
            "title": "Item title",
            "description": "Description",
            "quantity": 1,
            "unit_price": 50,
            "currency_id": "[FAKER][CURRENCY][ACRONYM]",
            "picture_url": "https://www.mercadopago.com/org-img/MP3/home/logomp3.gif"
        },
         {
            "title": "Item title 2",
            "description": "Description 2",
            "quantity": 1,
            "unit_price": 70,
            "currency_id": "[FAKER][CURRENCY][ACRONYM]",
            "picture_url": "https://www.mercadopago.com/org-img/MP3/home/logomp3.gif"
        }
    ],
    "marketplace_fee": 2.29
}
```

What no one can do with MP Marketplace solution (what I'd need to do):

```
{
    "items": [
        {
            "title": "Item title",
            "description": "Description",
            "quantity": 1,
            "unit_price": 50,
            "currency_id": "[FAKER][CURRENCY][ACRONYM]",
            "picture_url": "https://www.mercadopago.com/org-img/MP3/home/logomp3.gif",
            "marketplace_fee": 2.29
        },
         {
            "title": "Item title 2",
            "description": "Description 2",
            "quantity": 1,
            "unit_price": 70,
            "currency_id": "[FAKER][CURRENCY][ACRONYM]",
            "picture_url": "https://www.mercadopago.com/org-img/MP3/home/logomp3.gif",
            "marketplace_fee": 5.53
        }
    ]
}
```

So now it's impossible to develop a solution that cover this scenario through MP solution for marketplace.

Can any MP developer explain me why? And tell me when will that feature be released?

I appreciate the MP whole system on online payments, it is a pitty for me that I can't use it beacuse the missing feature which I am looking for since MP introduced the marketplace solution.

I hope you develop and release that feature soon, so I can migrate to MP (:

Thanks in advance.

**Comment by biaguerreiromeli** [comment]
Hola, @cawecoy 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a errores inesperados de la plataforma y sus integraciones.

**Tenemos un canal oficial súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
