### ISSUE TITLE
work in php 7.4 but in php 8 get error 

### ISSUE THREAD

**Issue by diarsaba** [mercadopago/devsite-docs#1430]
Deprecated: is_file(): Passing null to parameter #1 ($filename) of type string is deprecated in /Users/diarsaba/Documents/WEB/start/temp/base/complete/vendor/mercadopago/dx-php/src/MercadoPago/Config.php on line 65

I need to downgrade php to use mercadopago API

**Comment by biaguerreiromeli** [comment]
Hola, @diarsaba 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a errores inesperados de la plataforma y sus integraciones.

**Tenemos un canal oficial súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
