### ISSUE TITLE
Integracion con clientes de otros paises en Markeplace

### ISSUE THREAD

**Issue by bfacumat** [mercadopago/devsite-docs#1443]
Es posible realizando una integracion por tipo marketplace asociar clientes de varios de los paises soportados por MP?

Tengo funcionando una integracion en donde para cada pais de mis posibles clientes tengo una app creada, pero dede hace un tiempo MP me pide validar la identidad de mis cuentas en los otros paises y no lo puedo hacer ya que no tengo documento ni sociedades en estos paises.

Gracias!

**Comment by biaguerreiromeli** [comment]
Hola, @bfacumat 👋 

Le pedimos disculpas por la demora.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a preguntas o errores inesperados de la plataforma y sus integraciones.

**Tenemos un canal oficial súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
