### ISSUE TITLE
Formulario de Autorizacion no Funciona

### ISSUE THREAD

**Issue by Wagimo** [mercadopago/devsite-docs#1459]
Hola a todos.
Estoy implementando el cobro  haciendo uso de la integración tipo MarketPlace.  He creado la aplicación MarlketPlace tal y como lo indica la documentación y en el momento de querer vincular las cuentas de vendedores generando la URL,  no se despliega el formulario de Autorización, sino que por el contrario, me pide las credenciales de vendedor y cuando me autentico, me deja en el dashboard de la cuenta del usuario.  Esta es la URL que generé para la App :
https://auth.mercadopago.com.co/authorization?client_id=3130963227645687&response_type=code&platform_id=mp&state=cliente1&redirect_uri=https://hookb.in/Mq0PR8r89ohDRWppR6GP
La verdad no sé que esta sucediendo,  pero me gustaría que me colaboren para encontrar el error si es el caso o de ilustrarme la forma correcta de hacerle en el caso de que haya cambiado la forma de implementar dicha funcionalidad.

Muchas Gracias.

**Comment by biaguerreiromeli** [comment]
Hola, @Wagimo 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a errores inesperados de la plataforma y sus integraciones.

**Tenemos un canal oficial súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
