### ISSUE TITLE
Pago aprobado aparece mas de 1 vez

### ISSUE THREAD

**Issue by esabadot** [mercadopago/devsite-docs#1479]
El 22 de diciembre tenemos 2 pedidos en Woocommerce que fueron procesados exitosamente en mercadopago y que fueron informados inmediatamente en woocommerce al momento de cerrarse la venta. El tema es que 2 hs aproximadamente despues, tenemos nuevamente el informe de mercado pago de aprobación del pago, lo cual hace que los pedidos, que ya se encontraban en estado "completado" vuelvan al estado "procesando"

**Comment by biaguerreiromeli** [comment]
Hola, @esabadot 👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a errores inesperados de la plataforma y sus integraciones.

**Tenemos un canal oficial súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
