### ISSUE TITLE
select parcela mesma cor do fundo

### ISSUE THREAD

**Issue by eferros** [mercadopago/devsite-docs#1503]
campo de opções parcelamento aparece em branco ou da mesma cor do fundo 

imagem dos campos em branco 
![image](https://user-images.githubusercontent.com/18400134/148584779-83014af8-3791-485d-b55f-e8f7af4ddfbb.png)

imagem dos campos editados o css tema

.button, button:not(.components-button), input, select, textarea {
    color: var(--ctexto)!important;
}

![image](https://user-images.githubusercontent.com/18400134/148584496-668a8bb5-e050-4762-8f06-d0827aaaece7.png)

Obrigado!

**Comment by biaguerreiromeli** [comment]
Oi, @eferros 👋 

Pedimos desculpas pela demora e pelo inconveniente no seu fluxo de trabalho.

Mesmo sendo aberto, este espaço não pretende ser uma ferramenta de suporte a erros inesperados da plataforma e suas integrações.

Temos um canal oficial super preparado para solucionar rapidamente o seu caso.

Por isso, se o erro ainda persiste, compile toda a informação e acesse o link a seguir para compartilhar conosco o problema: https://www.mercadopago.com/developers/pt/support/center/contact

Muito obrigada pelo seu contato!
