### ISSUE TITLE
Orientação incorreta para credenciais de test user

### ISSUE THREAD

**Issue by adfonseca** [mercadopago/devsite-docs#1507]
## Context
Include:
- Articles and sections involved (with links).
- Checkout transparente - Teste sua integração: https://www.mercadopago.com.br/developers/pt/guides/online-payments/checkout-api/testing

- Screenshots to serve as examples.

![image](https://user-images.githubusercontent.com/52299041/148938658-a30befa7-b142-49bc-9e9a-29f2a943718d.png)

### Description
Ambas as credenciais public key e access token devem ser do usuário teste **vendedor**. Do usuário comprador só se deve usar o e-mail.

**Comment by biaguerreiromeli** [comment]
Oi, @adfonseca 👋 

Muito obrigada pelo seu contato e sua sugestão de melhoria na documentação. 

Já levamos os comentários para o time responsável pela manutenção desta doc!
