### ISSUE TITLE
Integracion MarketPlace

### ISSUE THREAD

**Issue by Wagimo** [mercadopago/devsite-docs#1533]
Buena tarde.
Estoy integrando la pasarela de pago como un MarketPlace en mi  E-commerce.  Siguiendo el tutorial, ya genero y obtengo los datos de autorización para cobrar a nombre de un vendedor. Producto de este proceso  obtengo el **access_token, refresh_token, public_key**, datos necesarios para operar  bajo este esquema y los cuales persisto en mi base de datos.
El problema que tengo es cuando intento hacer una compra utilizando las credenciales de test. 
Comienzo el proceso  creando una preferencia haciendo uso del Access_token del usuario vendedor que me autorizó  cobrar a nombre de el.  Este primer paso lo hace sin problemas, la preferencia se crea en Mercado Pago ya que la puedo consultar. posteriormente  cuando renderizo el botón de pago, en mi FrontEnd  utilizando el Id de  la preferencia y el Publick_Key asociada a la aplicación, y doy click en él, la pasarela de pago me arroja un error que dice: 
**Una de las partes con las que intentas hacer el pago es de Prueba**.
Como lo comenté líneas atrás,  **estoy utilizando solo credenciales de prueba para este proceso.** La verdad no sé que hacer y me gustaría que  alguien  me puede dar una luz sobre el tema para desatorarme, llevo varios días en esto.
Que estoy haciendo mal?
Muchas Gracias.

**Comment by biaguerreiromeli** [comment]
Hola, @Wagimo  👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a errores inesperados de la plataforma y sus integraciones.

**Tenemos un canal oficial súper preparado para solucionar rápidamente tu caso.**
Por eso, si el error aún persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por su contacto!
