### ISSUE TITLE
(idea) implementar marketplace_fee para envíos

### ISSUE THREAD

**Issue by israelpelayo** [mercadopago/devsite-docs#1548]
Hola. Gracias por todo su trabajo. Espero estar en el lugar correcto para compartir esta idea. 

Tengo un proyecto de marketplace donde, en principio, se cobrará una comisión fija por cada venta. En este sentido, el plugin hace su trabajo bastante bien dividiendo el pago para el vendedor y para el administrador del marketplace. El problema está en que tengo incluido un sistema de envío del paquete por distancias (concretamente el plugin Local Delivery Drivers for WooCommerce), lo cual hace que el costo de envío sea variable en función de la ubicación geográfica del comprador. Los envíos no los administra el vendedor sino, más bien, el administrador pero por medio de dicho plugin, y paga la comisión el repartidor. En las funciones para estas cuestiones que veo dentro de Mercadopago sólo veo "marketplace_fee", lo cual supongo que es la función que separa el pago para el vendedor y el pago para administrador.  Mi recomendación es que se implemente una función más, es decir, la comisión o tarifa para los envíos. En este sentido, pienso que, además de enviar el pago tanto al vendedor como al administrador del marketplace, debería implementarse un tercer pago: para el repartidor. 

Espero que esta idea tenga sentido. Al fin de cuentas, el servicio de una store o un marketplace en línea implica a) el trabajo del administrador, b) el trabajo del vendedor, c) el trabajo del repartidor. 

Mil gracias por todo su desarrollo y por su excelente trabajo.

**Comment by biaguerreiromeli** [comment]
Hola, @israelpelayo 👋 

¡Qué buena idea! 

Aun siendo abierto, este espacio no pretende servir como herramienta de contacto con el equipo interno de MELI y MP.

Pero no te preocupes -  **tenemos un canal oficial súper preparado para que compartas oficialmente tu resolución conosco**: https://www.mercadopago.com/developers/es/support/center/contact

¡Muchas gracias por tu contacto!
