### ISSUE TITLE
Translation missing: Mercado Pago API  (Version ingles)

### ISSUE THREAD

**Issue by vousys** [mercadopago/devsite-docs#169]
En esta pagina: https://www.mercadopago.com.ar/developers/en/reference
Falta la traduccion:

![image](https://user-images.githubusercontent.com/12813221/42054472-dff21dfc-7aea-11e8-8482-992d60845ef7.png)

**Comment by joelibaceta** [comment]
Solved https://github.com/mercadolibre/fury_devsite/pull/85
