### ISSUE TITLE
IPN: ejemplo en PHP usa el sdk legacy

### ISSUE THREAD

**Issue by vousys** [mercadopago/devsite-docs#171]
Chicos en esta URL, el ejemplo en PHP, esta usando el sdk viejo https://www.mercadopago.com.ar/developers/en/guides/notifications/ipn

![image](https://user-images.githubusercontent.com/12813221/42064138-791625da-7b0b-11e8-8bf3-00bc4bf645f6.png)

**Comment by joelibaceta** [comment]
@vousys gracias por el reporte, estaremos actualizando el snippet hacia la nueva versión del SDK.

**Comment by joelibaceta** [comment]
Fixed in https://github.com/mercadopago/devsite-docs/pull/172
