### ISSUE TITLE
Manejo de errores // Web tokenize y API 

### ISSUE THREAD

**Issue by vousys** [mercadopago/devsite-docs#176]
Chicos, seria muy útil que en la documentación de estas paginas:
https://www.mercadopago.com.ar/developers/es/guides/payments/web-tokenize-checkout/introduction
https://www.mercadopago.com.ar/developers/es/guides/payments/api/receiving-payment-by-card/

Donde se muestra la respuesta de la API, pongan como ejemplo que el response del 
$payment->save puede retornarte un status = NULL  y un array con diferentes errores si haces un dump del response

Te paso un ejemplo.
 
```
$response = $payment->save();
 
print_r($response);

(        
        [0] => Array
                        (
                            [code] => 2060
                            [description] => The customer can't be equal to the collector.
                            [data] => 
                        )

                )

        )

```
En este caso, yo creeria q el $payment->status deberia devolverme algun tipo de respuesta "rejected" en lugar de null, como para poder canalizar mejor la respuesta.

**Comment by joelibaceta** [comment]
@vousys tomamos el issue para devolver una colección bajo un atributo `errors` con informacion sobre el error.

Sobre la sugerencia de devolver "rejected". seria informacion falsa, ya que al no superar el proceso de validación de parámetros el request no fue enviado al API de pagos.

La validación que se sugiere hacer es 

if ($payment->status == null) {
    // Manejar el error
    echo $payment->errors
}
