### ISSUE TITLE
Suscripciones y Planes // No estan en el menu

### ISSUE THREAD

**Issue by vousys** [mercadopago/devsite-docs#181]
Chicos en el menu lateral, no habla de los planes y suscripciones
Solo llegas ahi si lo buscas en el input de search:
Urls como estas, serian utiles:
https://www.mercadopago.com.ar/developers/es/guides/subscriptions/api/create-subscription
https://www.mercadopago.com.ar/developers/en/guides/subscriptions/web-checkout/create-subscription

Tambien seria muy util, tener una referencia de como capturas los pagos mensuales que te va mandando via webhook (si es que lo hace)

**Comment by joelibaceta** [comment]
Es correcto, revisaremos el issue de que aun se vea en la búsqueda, estamos trabajando en ofrecer una nueva solución de suscripciones, la actual sera deprecada por lo que dejamos de incluirlo en la documentación.

**Comment by vousys** [comment]
Ha no me digas, que lastima porque estaba muy buena y la iba a implementar.
Aguardo entonces la nueva version! gracias por el soporte
