### ISSUE TITLE
¿Cual es la referencia correcta de la API de MercadoPago?

### ISSUE THREAD

**Issue by fberasategui** [mercadopago/devsite-docs#185]
Hay 2 versiones online actualmente de la referencia de la API:

1 - https://www.mercadopago.com.ar/developers/en/api-docs/

2 - https://www.mercadopago.com.ar/developers/en/reference

Pareciera que pertenecen a sitios web distintos, ya que tienen estilos diferentes.

La primera tiene mucha más información y describe Endpoints que en la segunda versión no aparecen.
Sin embargo, tiene algunos items de la lista que no muestran información, ejemplo: https://www.mercadopago.com.ar/developers/en/api-docs/basic-checkout/subscription-preferences/

La segunda tiene un estilo más parecido a la UI de OpenAPI (swagger), lo cuál me lleva a pensar que es más nueva.

¿Donde puedo obtener la lista definitiva de los endpoints que no están deprecados y los datos que reciben/devuelven?

**Comment by mminestrelli** [comment]
Hola @fberasategui la referencia es https://www.mercadopago.com.ar/developers/es/reference/, gracias por tu consulta y disculpas por la demora en la respuesta.

Te recordamos que por consultas técnicas podés escribirnos via https://developers.mercadopago.com

**Comment by fberasategui** [comment]
@mminestrelli nuevos dueños? Van a hacer algo con mis PRs?

Alternativamente (y de onda) usen cualquier templating engine para generar los SDKs a partir de la definición de la API que está en el repo de documentación. Sino tenés menos consistencia que el plan económico de mauri.
