### ISSUE TITLE
Mercado Pago Web Checkout en .NET

### ISSUE THREAD

**Issue by Jhordan92** [mercadopago/devsite-docs#217]
Hola,

Estoy realizando todos los pasos, creo la preferencia, agrego al payer, pero cuando llego al tema de "Lleva a tu comprador al checkout", solo está un ejemplo de PHP haciendo referencia a un init_point que no ubico. Me hace falta ese paso en .NET y saber que es el init_point, porque al generar un botón de compra, no veo tal objeto.

Agradezco la ayuda que puedan prestarme.

**Comment by mminestrelli** [comment]
Hola @Jhordan92 este canal es para reportar bugs o sugerencia de features, por dudas de uso por favor contactate con el equipo de soporte a través del formulario en el devsite: https://www.mercadopago.com.ar/developers/es/support.

Gracias!
