### ISSUE TITLE
How to cancell a qr payment await?

### ISSUE THREAD

**Issue by ARBIODOMO** [mercadopago/devsite-docs#219]
Una vez que inicie el pedido de pago por qr, se supone que muere en 10 mins o si mando otra solicitud la pisa... hay manera de cancelar una solicitud inciada?

**Comment by mminestrelli** [comment]
Hola @ARBIODOMO este canal es para reportar bugs o sugerencia de features, por dudas de uso por favor contactate con el equipo de soporte a través del formulario en el devsite: https://www.mercadopago.com.ar/developers/es/support.

Gracias!

**Comment by ARBIODOMO** [comment]
Ok, sería una sugerencia de feature, porque en https://www.mercadopago.com.ar/developers/es/support
no esta la documentacion... estarían buenos features para cancelar, actualizar, consultar el estado de la solicitud por qr... fuera de que la creo, no tengo como continuar con la misma
