### ISSUE TITLE
Inconsistencia respecto del sponsor_id en la documentación del resource Preference

### ISSUE THREAD

**Issue by fberasategui** [mercadopago/devsite-docs#243]
https://www.mercadopago.com.ar/developers/es/reference/preferences/_preferences/post/

Acá se indica que el endpoint puede devolver errores relacionados al `sponsor_id`, pero ese dato no es parte de las propiedades del objeto, según la misma documentación.

Tampoco encuentro la property en los SDK oficiales.

Ese endpoint acepta esa propiedad en particular o no?

**Comment by joelibaceta** [comment]
Solved in https://github.com/mercadopago/dx-dotnet/commit/98c50ab6cdb8ec143d2fc7d7d01b316a3bac9864

**Comment by joelibaceta** [comment]
Gracias @fberasategui por la observación, estaremos impactando la corrección en los SDKs
