### ISSUE TITLE
Actualizar referencia de API para payments/search

### ISSUE THREAD

**Issue by joelibaceta** [mercadopago/devsite-docs#255]
El atributo Payer como objeto no es un parámetro de búsqueda, sino únicamente el payer_id, actualizar documentación para reflejar esto.

**Comment by SebastianCBA** [comment]
Tengo el mismo problema! Alguna solucion? necesito poder filtrar pagos por email... la gente me paga por QR y necesito poder buscar por email o nombre o apellido los pagos y ninguno de esos parametros funcionan, solo el payer_id como dice joel... me devuelve lo siguiente:
`{
  "message": "the attribute payer.email is not a possible param",
  "error": "bad_request",
  "status": 400,
  "cause": [
  ]
}`

Alguna solucion por favor! Gracias de antemano.

**Comment by joelibaceta** [comment]
@SebastianCBA `payer.email` no es un parámetro de búsqueda, puedes consultar previamente por el `payer_id` usando el API de users.

**Comment by SebastianCBA** [comment]
Claro, pero calculá que viene un cliente al negocio y me dice que en la pc de casa me hizo el pago, pero no trae nada de nada y solo sabe su correo electronico o su nombre o su apellido... yo antes de entregar la mercaderia debo asegurarme que el pago este completado, de ahi que necesito poder buscar por ese parametro... vos me recomendas por cada pago, consultar el cliente para ver si el email coincide?

**Comment by joelibaceta** [comment]
@joelibaceta podes consultar al API de users para obtener el id del pagador a partir del email, el API de pagos no hace búsquedas sobre otros recursos, entiendo que debido a las dimensiones de datos que tendría que manejar.

**Comment by SebastianCBA** [comment]
donde esta la info de la API de users?

**Comment by joelibaceta** [comment]
@SebastianCBA me parece que no esta abierta, al parecer la unica manera de buscar por user, seria cargar el identificador en el campo de referencia.
