### ISSUE TITLE
Nueva arquitectura de pagos recurrentes

### ISSUE THREAD

**Issue by sebasira** [mercadopago/devsite-docs#256]
Estoy un poco confundido... 

Actualmente uso la API de MercadoPago con [sdk-java](https://github.com/mercadopago/sdk-java) en modo Basic Checkout para procesar pagos recurrentes con Preppaproval.

Segun un mail de soporte tecnico, los Preapproval están deprecados o pronto a deprecarse. Mi sistema se basa en esa metodologia de pagos para mantener, gestionar y administrar las subscripciones de los usuarios.

Cuando finalmente este desarrollada la nueva arquitectura en la que estan trabajando para los pagos recurrentes, dejara de funcionar los viejo (preapproval) de un dia para el otro?

Una de las razones por la que elijo el uso del Basic Checkout es para no tener que lidiar con certificados SSL y demás. Esta nueva arquitectura va a ofrecer un enfoque similar?

**Comment by joelibaceta** [comment]
@sebasira Estamos trabajando en un nuevo producto para suscripciones, por lo que retiramos la documentación de forma intencional para reducir la cantidad de integradores que tendremos que migrar a la nueva versión.
Las integraciones ya existentes seguirán funcionando, pero se trata de evitar nuevas integraciones hasta tener el nuevo producto listo.

**Comment by sebasira** [comment]
Muchas gracias @joelibaceta! Me deja mucho mas tranquilo la respuesta.

Espero, entonces, la nueva arquitectura! 

Cierro la pregunta
