### ISSUE TITLE
Actualizar URL de Crear Orden, en Pagos QR en Punto de Venta

### ISSUE THREAD

**Issue by FacundoSuarez** [mercadopago/devsite-docs#283]
La URL que aparece: 
[https://api.mercadopago.com/instore/qr/COLLECTOR_ID/EXTERNAL_ID?access_token=ACCESS_TOKEN](url) 
No funciona. Debe cambiarse a:
[https://api.mercadopago.com/mpmobile/instore/qr/COLLECTOR_ID/EXTERNAL_ID?access_token=ACCESS_TOKEN](url)

**Comment by Juanii95** [comment]
Fixed!
