### ISSUE TITLE
Notificaciones IPN se envian por POST

### ISSUE THREAD

**Issue by FacundoSuarez** [mercadopago/devsite-docs#290]
En la pestaña de las notificaciones aparece esto que envian un Post con 2 QueryParams. Esto es incorrecto al dia de la fecha. Llega un Json con un contenido similar al siguiente:

> {
  "data": {
    "id": "123123123"
  },
  "date_created": "2019-01-28T13:24:00.000-04:00",
  "type": "payment",
  "api_version": "v1",
  "id": 123123123
  "action": "payment.created",
  "user_id": 123123123,
  "live_mode": false
}

Sugiero arreglarlo rapidamente porque es una parte fundamental en el flujo de las integraciones

**Comment by joelibaceta** [comment]
@FacundoSuarez en realidad lo que estas recibiendo es un Webhooks, no un IPN por eso la firma es distinta.

**Comment by FacundoSuarez** [comment]
La documentacion en ese momento solo contemplaba las IPN.
