### ISSUE TITLE
Web tokenize - iframe events

### ISSUE THREAD

**Issue by ramiromd** [mercadopago/devsite-docs#296]
Hola, estoy utilizando el método de tokenización Web Tokenize Checkout para una integración en Uruguay. 
Me gustaría conocer, si existe la forma de saber si el iframe se cerró por los siguientes motivos:
1) La tokenización fue exitosa.
2) El usuario canceló la operación de tokenización.

**Comment by arielfr** [comment]
Hola @ramiromd perdón por la demora. Te respondo:

1. Una vez terminado el proceso de carga de tarjeta por el cliente el Javascript que estas insertando va a realizar un `POST` sobre el `<form />` que estas wrappiando con el `<script/>`. Te dejo un ejemplo:

```
<form action="/procesar-pago" method="POST">
  <script
    src="https://www.mercadopago.com.ar/integrations/v1/web-tokenize-checkout.js"
    data-public-key="ENV_PUBLIC_KEY"
    data-transaction-amount="100.00">
  </script>
</form>
```

Siguiendo el ejemplo anterior, una vez que el proceso de tokenización finalice se realizaría un `POST` al `action="/procesar-pago"`

2. Existe un evento para cuando el usuario cierra el modal, pero no es público **todavía.** Si lo usas no vamos a poder darte soporte en caso de que cambie. En caso de que lo quieras hacer podrías escuchar el evento `close` que esta attacheado al window.

Saludos
