### ISSUE TITLE
Error en código de IPN

### ISSUE THREAD

**Issue by sebaherrera** [mercadopago/devsite-docs#312]
En https://www.mercadopago.com.ar/developers/es/guides/notifications/ipn, aparte de que volvió el error de sintaxis a la línea 10 (falta el paréntesis final), el código no contempla las excepciones "Payment not found" o "Merchant order not found" (entre otras) y termina imprimiendo igualmente el mensaje "Totally paid. Release your item" aunque eso sea totalmente incorrecto.

**Comment by faculezcano** [comment]
Falta igualmente el break del primer case del switch topic (abajo de linea 10), por que si el topic es 'payment' ejecuta tambien el case de merchant_order, termina intentando levantar un merchant_order con id de payment y nunca funciona para payments.

En linea 10 cambie el `->order_id` por `->order->id` ya que esa propiedad no existe en Payment.

El otro error en la parte que cuenta los pagos, se usan los stdObjects como arrays y php se queja, es necesario cambiar linea 17 y 18
`$payment['status'`] por `$payment->status`
`$payment['transaction_amount']` por `$payment->transaction_amount`

Creo que por ultimo linea 24 falla el `count($merchant_order->shipments)` por lo menos cuando no hay envios.

Se nota el copy paste del sdk legacy, ni testeado el ejemplo jaja

**Comment by sebaherrera** [comment]
Algunas de esas cosas las probé, pero me cansé del tiempo que estaba desperdiciando y volví a la versión anterior. Tratándose de un agregador de pagos, creo que es fundamental saber si algo se pagó (y sin posibilidad de equivocación, como pasa ahora), por lo cual debería crearse directamente una clase en el SDK que simplifique eso.
