### ISSUE TITLE
Faltan los requisitos de salida a producción

### ISSUE THREAD

**Issue by miltonbrandes** [mercadopago/devsite-docs#33]
Falta subir los requisitos de salida a producción que se encuentran en el [viejo devsite](https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/appliance-requirements/) Que son importantes para la homologación de un CHO Personalizado (API)

**Comment by joelibaceta** [comment]
Gracias por la observación, tomo el issue.

**Comment by Danasb** [comment]
Voy a agragar los requisitos para salir a prod en la intro de payments -> API.

**Comment by mminestrelli** [comment]
Fixed in #48
