### ISSUE TITLE
compra de pines paysafecard

### ISSUE THREAD

**Issue by facundo55** [mercadopago/devsite-docs#398]
Podrían agregar la posibilidad de comprar pines de paysafecard, ya que es muy difícil desde sudamerica (o por lo menos desde argentina) comprar online pines. Los cuales son muy importantes para cargar credito a las cuentas de apuestas deportivas o casinos en linea e inclusive cargar dinero a netteler, por ejemplo

**Comment by mminestrelli** [comment]
Hola @facundo55!, este espacio es para reportar inconvenientes o potenciales mejoras que pueda tener la documentación de los productos de Mercado Pago. 

Recomendamos dirigir tu sugerencia a la [sección de ayuda de Mercado Pago](http://ayuda.mercadopago.com.ar/ayuda)
