### ISSUE TITLE
Desconto não se aplica no mercado pago

### ISSUE THREAD

**Issue by carollz** [mercadopago/devsite-docs#399]
Ao disponibilizar um desconto na loja e escolher o Checkout Básico o desconto/créditos não se aplica na janela do módulo, ou seja, exibe apenas na loja e na janela exibe o valor normal do produto, dessa forma o cliente vê o desconto, porém não consegue pagar o valor correto.. somente o valor sem desconto pelo mercado pago.

Uso opencart 3.0.3.1

**Comment by mminestrelli** [comment]
@carollz este espaço é para relatar problemas ou possíveis melhorias na documentação dos produtos do Mercado Pago. Para consultas de suporte, acesse o site do desenvolvedor http://mercadopago.com.br/developers/pt/support/.

Muito obrigado!
