### ISSUE TITLE
¿Documentación de Mercadoenvíos?

### ISSUE THREAD

**Issue by sebaherrera** [mercadopago/devsite-docs#413]
Hola. Ví que actualizaron la documentación del Web Checkout (por cierto, quedó muy bien) pero no hay ninguna referencia a Mercadoenvíos. ¿Se olvidaron o ya no va a estar más disponible?

Si no piensan ofrecerlo más, por favor avisen con tiempo en el changelog. No anden rompiendo sitios alegremente como ya hicieron con el plugin de Woocommerce.

**Comment by jpmelnik** [comment]
Hola. ¿Mercado envíos sigue estando disponible SOLO para el Checkout básico? ¿Hay alguna novedad para el checkout Personalizado?

**Comment by sebaherrera** [comment]
Lo que te puedo decir es que, en los sitios que hoy tienen Mercadoenvíos, sigue saliendo la versión anterior del checkout básico. Así que seguramente la situación siga igual que hasta ahora.

**Comment by Juanii95** [comment]
Hola @sebaherrera ! Mil disculpas por la demora en responder. Recordá que este espacio es únicamente para proponer cambios en la documentación del Sitio de Developers. Para consultas, por favor ingresá a [Soporte](https://www.mercadopago.com.ar/developers/es/support/) y completá el formulario de soporte para developers, así podemos ayudarte de manera efectiva.

**Comment by sebaherrera** [comment]
Pero justamente mi pregunta es sobre documentación que desapareció hace más de dos meses. El servicio sigue funcionando (al menos por el momento) pero no explican cómo implementarlo. Saludos.
