### ISSUE TITLE
Web tokenize - Angular 4 sin Post

### ISSUE THREAD

**Issue by asztern** [mercadopago/devsite-docs#426]
Hola, estamos implementando el Web Tokenize Checkout en una aplicacion que utiliza Angular 4. Como saben en Angular no se puede hacer postback, con lo cual no podemos utilizar el method="post" del Form. Hay alguna otra forma en que podamos implementarlo sin hacer postback o bien que sea compatible con Angular?

Si agregamos la directiva ngNoForm, permite el postback, pero despues da error en ASP.NETCore por el Single Page Application: 

InvalidOperationException: The SPA default page middleware could not return the default page '/index.html' because it was not found, and no other middleware handled the request

Agredeceria me indiquen alguna otra opcion ya que necestimos recuperar la tarjeta tokenizada para nuestro proyecto.

**Comment by Juanii95** [comment]
Hola @asztern ! Mil disculpas por la demora en responder. Recordá que este espacio es únicamente para proponer cambios en la documentación del Sitio de Developers. Para consultas, por favor ingresá a [soporte](https://www.mercadopago.com.ar/developers/es/support/) y completá el formulario de soporte para developers, así podemos ayudarte de manera efectiva.
