### ISSUE TITLE
Componente React para Web Checkout

### ISSUE THREAD

**Issue by mastepanoski** [mercadopago/devsite-docs#427]
Se necesitaria mejor soporte para la integración del Web checkout específicamente con ReactJS. Actualmente para integrarlo en plataformas como NextJS o en soluciones que se requiere acceso programático a Javascript hace que la nueva forma de personalización (modal principalmente) no se adecue del todo a las recomendaciones de React, tanto en la forma de carga del script necesario, como las cuestiones de seguridad, en cambio la versión del render (render.js de mptools) es más flexible y adaptable.
Todas las opciones personalizables como colores, id de preferencias, podrían aplicarse como propiedades de un React Component. Tener en cuenta también los entornos SSR también.

**Comment by sebaherrera** [comment]
No lo probé, pero debería funcionar el módulo para Node.js https://www.npmjs.com/package/mercadopago. Yo hago eso con algunas dependencias de un sitio basado en Angular.

**Comment by mastepanoski** [comment]
Ya he probado con ese módulo desde backend, pero una vez se obtiene el link generado a partir de la preferencia hacerlo de la forma sugerida en la documentación no se adecua correctamente con la arquitectura unidirectaional data flow de react; desarrollar en React sobre todo basándose en componentes comportamentales y presentacionales es una cosa distinta al hacerlo en Angular, ni hablar si se quiere integrar con SSR en plataformas como NextJS o Electrode. Es por ello que el componente más antiguo (render.js de mptools) no contemplado en el módulo NPM (que es para backend esencialmente), ofrece mayor flexibilidad que la nueva especificación que acota más su uso a determinados flujos de operación. Creo que al menos la opción programática no debería perderse sino no se va a dar un soporte oficial para otros toolkits.

**Comment by Juanii95** [comment]
Hola @mastepanoski ! Mil disculpas por la demora en responder. Recordá que este espacio es únicamente para proponer cambios en la documentación del Sitio de Developers. Para consultas, por favor ingresá a [soporte](https://www.mercadopago.com.ar/developers/es/support/) y completá el formulario de soporte para developers, así podemos ayudarte de manera efectiva.
