### ISSUE TITLE
Select Currency can't run Mercadopago.setPublishableKey(key) again?

### ISSUE THREAD

**Issue by vinstweb** [mercadopago/devsite-docs#441]
There is a select list of currency ['BRL', 'ARS']
Open the web run **Mercadopago.setPublishableKey(BRL_Key)**, and when I select the currency ARS, it should run **Mercadopago.setPublishableKey(ARS_Key)**, but not working .
so, I want to know what should i do.

**Comment by Juanii95** [comment]
Hola @vinstweb ! Para consultas sobre este tema, por favor ingresá [aquí](https://www.mercadopago.com.ar/developers/es/support/) y completá el formulario de soporte para developers, así podemos ayudarte de manera efectiva.
