### ISSUE TITLE
Suscripciones

### ISSUE THREAD

**Issue by jpmelnik** [mercadopago/devsite-docs#469]
¿La nueva versión no acepta suscripciones?

**Comment by Piuma14** [comment]
Venía justamente a preguntar lo mismo, porque volvi a la versión 3.1.1 para poder seguir cobrando con suscripción.

**Comment by Juanii95** [comment]
Hola @jpmelnik ! Mil disculpas por la demora en responder. Recordá que este espacio es únicamente para proponer cambios en la documentación del Sitio de Developers. Para consultas, por favor ingresá a [soporte](https://www.mercadopago.com.ar/developers/es/support/) y completá el formulario de soporte para developers, así podemos ayudarte de manera efectiva.

**Comment by fgilio** [comment]
En caso de que le sirva a alguien...
La API v0 de suscripciones (pre approvals) está en mantenimiento o por ser reemplazada por una nueva API. Mientras tanto, quitaron la documentación y toda mención del sitio para evitar que más proyectos continúen integrando esta versión "legacy" que probablemente sea 100% reemplazada (esto último es interpretación mía).
