### ISSUE TITLE
URL de retorno para Smart Checkout no especifica si es para modal o redirección

### ISSUE THREAD

**Issue by roelmagdaleno** [mercadopago/devsite-docs#496]
Buen día, acabo de integrar Smart Checkout de MercadoPago. La integración ha sido perfecta, sin embargo me queda la duda en la redirección hacia la URL de retorno cuando el usuario paga el producto.

En la [documentación](https://www.mercadopago.com.mx/developers/es/guides/payments/web-payment-checkout/advanced-integration/#bookmark_url_de_retorno) dice que podemos establecer la URL e incluso definir si debe redirigir automáticamente, sin embargo esto no sucede en mi caso.

Cabe destacar que estoy usando el modo de ventana modal, estoy llegando a pensar que no se puede en este modo y ¿solo se podría en el modo de redirección?

Si es así, deberían especificarlo en la [documentación](https://www.mercadopago.com.mx/developers/es/guides/payments/web-payment-checkout/advanced-integration/#bookmark_url_de_retorno).

Saludos.

**Comment by andreszs** [comment]
Estimado, he notado lo mismo, al terminar o cancelar un pago (c/ventana modal), se vuelve simplemente al lugar que indica tu `action `del form original.

Si cambias el `method `del form, en vez de `POST ` pones `GET `, al terminar el pago se redirige a la URL indicada en el valor `action` del form, **pero con los siguientes parametros adicionales en la URL** que podes obtener con `$_GET`:

![image](https://user-images.githubusercontent.com/10298071/66204900-64099f80-e682-11e9-8d0d-c5f1125aa575.png)

Como ves la URL que indicaste en `back_urls` se recibe como parte del parametro `back_url`... es totalmente bizarro, lo se. Tambien te llegan todos los params mostrados, que en principio son tentadores de usarlos, pero tenes que **tomarlos con pinzas** porque el usuario malicioso (o sea todos) puede simplemente editar la URL para cambiar los ID o el estado del pago, por ejemplo, transformar _rejected_ en _approved_. De mas esta decir que no pienso usar estos valores para nada, todos los resultados los voy a procesar mediante el IPN.

Sobre **IPN**, la documentacion y los ejemplos estan todos mal, despues voy a crear un PR con un ejemplo de IPN parser que se ajuste a lo que realmente recibis en la URL. (al [ejemplo ](https://www.mercadopago.com.ar/developers/es/guides/notifications/ipn/)hasta le falta un parentesis, se nota que jamas lo probaron) Tampoco podes asumir que al obtener un `merchant_order` por IPN inmediatamente podes buscar el `payment` correspondiente, como hace el ejemplo: el payment puede tardar varios minutos en aparecer, y se recibe en un segundo IPN.

**Comment by roelmagdaleno** [comment]
Gracias, lo del GET lo probé ayer y es muy cierto lo que dices, no es totalmente seguro. Por otra parte, estoy usando Laravel y creo que ejecutaré el POST y dentro de mi controlador voy a procesar los datos y redirigir desde ahí según sea el tipo de respuesta.

Lo malo es que esa acción que haré no me conviene porque al momento de hacer eso se me liberan unas casillas en tiempo real que no deberían desbloquearse ya que otro usuario podría elegirse y pudiese existir duplicidad en mi aplicación.

Y sin embargo podría existir otra opción donde agregas un listener:

```
window.addEventListener("message", (event) => {
   let dataType = event.data.type;
});
```

La API de MercadoPago lanza unos postMessage y hasta donde he registrado lanzan eventos como "close" y "submit", entre otros. Esto es en JavaScript.

He probado ejecutar código dentro de ese evento "submit" pero al parecer solo puedes ejecutar código muy sencillo, lo que yo traté de ejecutar fue mandar un mensaje en tiempo real y eso no funcionó.

Por otra parte, tenemos el evento "close" donde se puede ejecutar código pero solo funciona cuando el usuario cierra la ventana modal desde el ícono de cerrar.

Así que, si algún desarrollador de MercadoPago ve esto, creo que necesitamos una opción que no haga redirect y que retorne los valores del pago realizado usando solo JavaScript. ¿Hay algún repositorio dónde sugerir esta idea?

**Comment by roelmagdaleno** [comment]
@andreszs 

Bueno, traigo una solución a este problema lo acabo de probar.

Ya ven que estamos creando un `<form action="/procesar-pago"> <script...></script> </form>`, el problema actual de este formulario es que cuando se abre la ventana modal para que el usuario page el último proceso es dar click al botón "Volver a la Tienda", lo cual hace que ejecute el action del formulario creado y rediriga hacia la URL del action especificado.

Pero ahora acabo de descubrir que en el valor del action puede ir `javascript:void(0)`, quedando como:

`<form action="javascript:void(0)"> <script...></script> </form>`

Esto lo que hace es ignorar el submit y así ya no te redirige a otra URL, sin embargo, la ventana modal se cierra después del click en el botón. Ya es un avance.

Ahora, ¿cómo capturamos los datos de respuesta del pago efectuado? Y otra pregunta, ¿cómo ejecutamos código extra después del submit ignorado?

MercadoPago lanza unos eventos usando `window.postMessage()` y nosotros podemos escucharlos usando:

```
window.addEventListener("message", (event) => {
   if (event.origin !== 'https://www.mercadopago.com.mx' || ! event.data.type) {
     return;
   }

   let dataType = event.data.type; // "close", "submit", etc...

   if (dataType === 'submit') {
      // Tu funcionalidad a ejecutar...
      const paymentData = event.data.value; // Es un arreglo con la respuesta del pago procesado.
      return;
   }
});
```

No es tan complicado y es una alternativa a usar hasta que los desarrolladores de MP mejoren el Smart Checkout en este aspecto.

Suerte en sus desarrollos!

**Comment by andreszs** [comment]
Interesante lo que propones, aunque ese `window.postMessage()` que dices no esta documentado, es una alternativa para **evitar una redireccion** que el usuario pueda ver, al tiempo que retornas el resultado (inicial) del pago.

No se como será tu implementación , pero recordemos que algunos pagos pueden **demorar unos minutos** en acreditarse, por lo que yo solo enviaría al server los **ID del pago y del merchant_order** obtenidos en ese `postMessage()` para volver a chequear en unos minutos si el pago se acreditó. Esto es, como alternativa o complemento a las notificaciones IPN.

**Comment by roelmagdaleno** [comment]
@andreszs No, no está documentado pero si entras al código minificado del Smart Checkout encuentras una parte que dice `window.postMessage()`, y dije, pues está mandando unas peticiones al cliente...

En mi caso me conviene de esta manera porque mi aplicación es sobre el usuario tiene que elegir unos asientos en tiempo real y este se bloquea para los demás usuarios así que no pueden escoger el mismo asiento; el problema era que cuando cerraba la ventana modal y redirigía al usuario a la URL del action, el asiento se liberaba provocando una posible duplicidad en mis registros. Con este método ya no sucede.

Y lo de los pagos en acreditarse es muy cierto y la lógica que mencionas sería la mejor forma de guardar y comparar los pagos usando el IPN. Voy a ver si hago un pull request a la documentación documentando este método.

**Comment by andreszs** [comment]
Dale, te comento que recien publique un PR que soluciona errores basicos del ejemplo PHP de IPN, mira el #501 para mas detalles. Saludos!

**Comment by gquagliano** [comment]
Cabe aclarar que estos eventos no se disparan en mobile, donde el botón redirecciona a MercadoPago, y que `event.data` no siempre contiene un objeto, ejemplo:

![image](https://user-images.githubusercontent.com/22332988/73667704-6bb67080-4683-11ea-9992-ec0d47540da9.png)

Sería bueno contar con un mecanismo oficial y documentado para:

- Escuchar eventos, incluso en mobile (podría ser un llamado a una función con un callback para continuar con el redireccionamiento cuando termine nuestro proceso).
- Generar el botón dinámicamente (si se genera la preferencia mediante ajax no encuentro forma de generar un nuevo botón o actualizar el existente).
- Iniciar el proceso de pago sin depender del botón.

Estoy investigando el código fuente a ver qué podemos inventar, pero no es la manera...

Gracias.
Saludos.

**Comment by nicoseijas** [comment]
Hola @andreszs @roelmagdaleno @gquagliano, estoy reviviendo un ticket de hace tiempo pero quería consultar si lograron encontrar una solución ya que me encuentro actualmente con el mismo problema

Saludos

**Comment by gquagliano** [comment]
@nicoseijas Si, la solución fue no usarlo 😅. Parece que no tiene soporte, o no está documentado. Se hizo un checkout personalizado, lo cual no quiere decir que no haya que adivinar unas cuantas cosas más para lograr implementarlo. Paupérrima la documentación en general, ML no responde, arreglátela como puedas... 🤷‍♂️.

**Comment by roelmagdaleno** [comment]
@nicoseijas La verdad es que concuerdo con @gquagliano. Al final uno termina usando el checkout personalizado y hay que estar adivinando.

Aunque si llegas a encontrar alguna solución, estaría bien que lo compartieras. :)

**Comment by gquagliano** [comment]
@roelmagdaleno No creo que valga la pena seguir haciendo ingeniería inversa a una API cerrada y privada. Si fuera un error del SDK publicado en GitHub, quizás se podría colaborar (quizás...). Pero el problema está adentro de ML y la respuesta tendría que venir de su parte (lo de «arreglátela como puedas» no se lo decía yo a @nicoseijas, es lo que nos dice ML a todos nosotros.)

**Comment by andreszs** [comment]
@nicoseijas Al final deje el metodo POST, pero mantengo la politica original de usar el form modal para usuarios **desktop** y la redireccion para usuarios **mobile**, de esta manera:

```
<form data-actbutton="<?= $days ?>" action="<?= $_SERVER['REQUEST_URI'] ?>" method="POST" class="hidden">
	<? if($is_desktop_user){ ?>
		<!-- Form Modal -->
		<script
			type="text/javascript"
			src="https://www.mercadopago.com.ar/integrations/v1/web-payment-checkout.js"
			data-button-label="Activar"
			data-preference-id="<?= $preference->id ?>">
		</script>
	<? }else{ ?>
		<!-- Redirect -->
		<div><a href="<?= $preference->init_point ?>" class="mercadopago-button">Activar</a></div>
	<? } ?>
</form>
```

**Segun mis pruebas esto funciona y vuelve siempre a la URL indicada**, tanto en sandbox como en producción, ya sea que la compra se concrete o se cancele. Asi que evidentemente han corregido este bug en alguna actualización reciente.

**Comment by abelgascia** [comment]
Hola! Comento acá porque ya no encuentro solución y MercadoPago no responde los tickets.. Estoy utilizando el web-payment-checkout en React con el sistema de Redirect (Porque el modal por alguna razón funciona cuando quiere) y el procesamiento de pagos y todo funciona correctamente, excepto el redireccionamiento de las back_urls... Tampoco aparece ningún botón que diga "Volver a...", "Volver a Mi Tienda" o algo por el estilo. ¿Tienen alguna idea de cómo poder solucionar esto? Como digo, hace tiempo consulté mediante tickets en la plataforma de MercadoPago pero no hay caso. Agradezco su tiempo!

**Comment by MercadoPagoDevelopers** [comment]
Hola a todos, 

Antes que nada les pedimos disculpas por las demoras en la devolución desde nuestro lado.

Queremos contarles que el error mencionado con las Backs_urls se ha identificado y se está trabajando para obtener una solución a todas las situaciones. Por el momento, solo es posible utilizar las backs_url de manera correcta en el modo redirect, ya que en el modo modal no es necesario porque para volver a tu sitio toma la URL del form action, como mencionaron.

Por último, recuerden que siempre que tengan inconvenientes con el funcionamiento de nuestros productos, cuentan con nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos ayudarlos.

Saludos.
**El equipo de desarrolladores de Mercado Pago**.

**Comment by alemdg** [comment]
POR QUE EN UN CELULAR APARCE "Bajá la app y llevá tu plata y tarjetas en el celular.", por que NO HAY un BOTON para cerrar el modal?

**Comment by francog54** [comment]
este mercadopago es un loquillo

**Comment by carlosamn** [comment]
Saludos, el modal en desktop tiene scroll cuando el pago es exitoso y muchos usuarios no saben que hacer cuando termina el proceso de pago y no ven el botón de "Volver al Sitio", ya que está en la parte de abajo.

**Comment by LucianoRicardo737** [comment]
Mismo problema, tengo el checkout pro y no puedo recuperar los datos salvo cuando el cliente aprieta volver al sitio, parece absurdo que mercadolibre deje cosas mal desarrolladas. Y ni hablar de la documentación, tenes que adivinar la mitad.
