### ISSUE TITLE
Agregar opciones de personalización en Smart Checkout

### ISSUE THREAD

**Issue by andreszs** [mercadopago/devsite-docs#497]
## Context
[Personalización de Smart Checkout](https://www.mercadopago.com.ar/developers/es/guides/payments/web-payment-checkout/customizations/)
[Personalización de Web Tokenize Checkout](https://www.mercadopago.com.ar/developers/es/guides/payments/web-tokenize-checkout/personalization/)

### Description
En el **Smart Checkout**, seria bueno que agreguen las mismas opciones del Web Tokenize mode, a saber:

![image](https://user-images.githubusercontent.com/10298071/66123252-f002c500-e5b7-11e9-80f3-d065f0541ab1.png)

Esto permitiria cambiar el texto "_Productos_" por algo mas descriptivo, generando una mejor experiencia para el comprador. Cambiar del _Smart_ al _Web Tokenize_ solo por esto no se justifica, seguramente lo pueden implementar en cuestión de minutos. Gracias desde ya.

**Comment by Juanii95** [comment]
Hola @andreszs como estas?
A diferencia de Web Tokenize Checkout, Smart checkout toma los atributos de los datos de la preferencia. Por lo que los data-summary no tendrían efecto.

Nos llevamos el punto de mejora para que se pueda modificar el titulo "productos" y lo elevaremos con nuestro sector encargado.

Saludos,
