### ISSUE TITLE
Arreglos a ejemplo PHP de IPN

### ISSUE THREAD

**Issue by andreszs** [mercadopago/devsite-docs#501]
## Context
[Ejemplos PHP de IPN](https://www.mercadopago.com.ar/developers/es/guides/notifications/ipn/)

### Description
En el ejemplo PHP de recepción IPN, hay errores como:
- Falta un parentesis
- Faltan los `break `del `switch`
- Al recibir un `topic='payment'`, el id llega en un parámetro data_id, no id
- Al recibir un `topic='payment'`, `$payment->order_id` es `NULL`, se cambió para obtenerlo de `$payment->order->id`.

Estoy creando un PR para arreglar esto en los 3 idiomas.

### Advertencia

A pesar de estos arreglos, el ejemplo sigue incompleto. Por qué? Porque el ejemplo solo busca los pagos en `$merchant_order`, y por algun motivo, mis compras de prueba retornan **vacio** el objeto `$merchant_order->payments`, **incluso despues** que el pago se acreditó y recibi un segundo IPN con `topic=payment`. **A las personas que MP si les actualice correctamente su merchant_order al recibir un pago, el ejemplo les deberia funciona perfectamente.**

Avisen si hay otro error, de todos modos pienso hacer un ejemplo nuevo y completo que publicaré en mi sitio personal si el PR es rechazado aquí.

**Comment by Juanii95** [comment]
Hola @andreszs !!

Muchas gracias por la contribución. Realizamos unos cambios en el PR que nos enviaste, cuando lo aceptes lo mergeamos.

Saludos!

**Comment by andreszs** [comment]
@Juanii95 gracias, ya acepte las sugerencias que hicieron, ahora deberian poder hacer merge sin problemas.

Estaria interesante aclarar en la documentacion, que la URL que recibe IPN tambien puede recibir Webhooks, porque ahora eso en ningun momento es informado y se presta a grandes confusiones. Tampoco explican en ningun lado cual es la diferencia entre IPN y Webhook, ventajas o desventajas de c/u, etc., este tema de tener 2 metodos que reciben datos similares genera mas confusión que otra cosa. Tal vez sea hora de **combinar IPN + Webhook en un solo sistema**, para ahorrarnos tanta confusión?
