### ISSUE TITLE
Sugerencia de visualización en celulares

### ISSUE THREAD

**Issue by serfalco** [mercadopago/devsite-docs#504]
Disculpen mi intromisión y mi ignorancia, sucede que estoy viendo que al momento de efectuar el pago en la compu se ve muy bien las opciones de pago tarjetas, efectivo, crédito débito etc, pero en el modo celular se ve muy feo, ya que no muestra ningún logo y queda un bloque o caja bastante grande poco amigable que da sensación de falla o falta de algo! 
![mercadopago](https://user-images.githubusercontent.com/56321016/66428904-51c69300-e9ed-11e9-94ba-417aa4e066d0.png)

**Comment by Juanii95** [comment]
Hola @serfalco ! Mil disculpas por la demora en responder. Recordá que este espacio es únicamente para proponer cambios en la documentación del Sitio de Developers. Para consultas, por favor ingresá a [soporte](https://www.mercadopago.com.ar/developers/es/support/) y completá el formulario de soporte para developers, así podemos ayudarte de manera efectiva.
