### ISSUE TITLE
Marketplace has an invalid release range configuration. Con usuario TEST

### ISSUE THREAD

**Issue by AlanAlc** [mercadopago/devsite-docs#516]
Al probar un Advanced_Payment con Split como lo dice la documentación:

https://www.mercadopago.com.ar/developers/es/guides/marketplace/advanced-payments/receive-split-payments/

en específico:

curl -X POST \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    'https://api.mercadopago.com/v1/advanced_payments?access_token=MKT_ACCESS_TOKEN' \
    -d '{...}'

con parámetros:

{
  "payer": {
    "email": "test@user.com"
  },  
  "payments": [
    {
      "payment_method_id": "visa",
      "payment_type_id": "credit_card",
      "token": "jhuyt786r5yhfcgjvhkuoy7t86r75erdfhcgv",
      "transaction_amount": 1000,
      "installments": 1,
      "processing_mode": "aggregator"
    }
  ],
  "disbursements": [
    {
      "amount": 200,
      "external_reference": "ref-collector-1",
      "collector_id": 44444444,
      "application_fee": 20,
      "money_release_days": 30
    },
    {
      "amount": 800,
      "external_reference": "ref-collector-2",
      "collector_id": 55555555,
      "application_fee": 80,
      "money_release_days": 30
    }
  ],
  "external_reference": "ref-transaction"
}

Utilizando cURL::

$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://api.mercadopago.com/v1/advanced_payments?access_token=MKT_ACCESS_TOKEN');
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n  \"payer\": {\n    \"email\": \"test_user_39130802@testuser.com\"\n  },  \n  \"payments\": [\n    {\n      \"payment_method_id\": \"visa\",\n      \"payment_type_id\": \"credit_card\",\n      \"token\": \"abc14fc79256cda6d2208864d98ec63a\",\n      \"transaction_amount\": 1000,\n      \"installments\": 1,\n      \"processing_mode\": \"aggregator\"\n    }\n  ],\n  \"disbursements\": [\n    {\n      \"amount\": 1000,\n      \"collector_id\": 462760739,\n      \"application_fee\": 20\n    }\n  ]}");
curl_setopt($ch, CURLOPT_POST, 1);curl_setopt($ch, CURLOPT_POST, 1);

$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}

var_dump($result);
curl_close($ch);

la respuesta es siempre:

string(214) "{"error":"bad_request","message":"Marketplace has an invalid release range configuration.","status":400,"cause":[{"code":400065,"description":"Marketplace has an invalid release range configuration.","data":null}]}"

En la cuenta test que funciona de Marketplace modifiqué la fecha de disponibilidad del dinero (desde https://www.mercadopago.com.mx/settings/release-options) pero el resultado es el mismo.

No hay documentación sobre este error en ningun lado, no está listado en la referencia. 

¿Alguien sabe qué está pasando?

**Comment by Juanii95** [comment]
Hola @AlanAlc ! Para consultas sobre este tema, por favor ingresá [aquí](https://www.mercadopago.com.ar/developers/es/support/) y completá el formulario de soporte para developers, así podemos ayudarte de manera efectiva.
