### ISSUE TITLE
error de formateo 

### ISSUE THREAD

**Issue by javicaceres** [mercadopago/devsite-docs#518]
## Context
Include:

https://www.mercadopago.com.ar/developers/es/guides/gateway/general-considerations/reconciliation/

![image](https://user-images.githubusercontent.com/32305374/67204206-62124100-f3e3-11e9-9a73-4dcf8f8afcc1.png)

### Description
Falló el formateo de markdown luego de: 
Conciliar vía API
Realizando un GET al endpoint /payments de la API de Mercado Pago puedes obtener el listado de operaciones...

**Comment by mminestrelli** [comment]
Gracias @javicaceres, lo sumamos a la próxima versión!
