### ISSUE TITLE
Referencia de API, objeto payment: ID debería ser Long

### ISSUE THREAD

**Issue by andreszs** [mercadopago/devsite-docs#526]
## Context
https://www.mercadopago.com.ar/developers/es/reference/payments/resource/

### Description
El valor ID no es tipo **Integer**, deberia ser **Long**. En PHP de 64 bits es manejable, pero para MySQL un tipo integer (unsigned) esta limitado a **4294967295** y MercadoPago ya excedió esa cantidad de transacciones hace tiempo. Atencion con otros tipos de datos que tal vez deberian ser Long también, como ser **orders > id**. 

Parece que no se pueden crear pull requests para editar la Referencia de API.

![image](https://user-images.githubusercontent.com/10298071/67620919-47283e00-f7e2-11e9-9b29-9352b33d697d.png)

**Comment by MercadoPagoDevelopers** [comment]
Hola @andreszs,
 
¡Gracias por escribirnos!
 
Ante todo, te pedimos disculpas por la demora en la devolución. Tomamos el caso y ya [implementamos el cambio](#671 ), el mismo se impactará la semana próxima.

Saludos, 
**El equipo de desarrolladores de Mercado Pago**
