### ISSUE TITLE
Faltan la ips de donde mercadopago envia las notificaciones

### ISSUE THREAD

**Issue by Leemonn** [mercadopago/devsite-docs#542]
En la seccion de notificaciones deberian estar las ips de donde se envian las notificaciones para poder agregarlas al whitelist en el backend.

**Comment by pabal1708** [comment]
Hola @Leemonn , Como estas?

Te informamos que el canal correcto para este tipo de consultas es mediante soporte en https://www.mercadopago.com.ar/developers.

Que tengas buena tarde.

Saludos
