### ISSUE TITLE
Worng parameters on customers and stored cards documentation.

### ISSUE THREAD

**Issue by TiagoAndreAlmeida** [mercadopago/devsite-docs#553]
on node sample code, method to create a card should be: 
`mercadopago.card.create(card_data).then(function (card) `
with card on singular not plural.
on documentation now is:
`mercadopago.cards.create(card_data).then(function (card) `

Another thing wrong is the parameter customer on card_data object, should be:
```
card_data = {
    "token": "9b2d63e00d66a8c721607214cedaecda",
    "customer_id": customer.id
  }
```
on documentation now is:
```
card_data = {
    "token": "9b2d63e00d66a8c721607214cedaecda",
    "customer": customer.id
  
}

**Comment by MercadoPagoDevelopers** [comment]
Hola Tiago,
 
¡Gracias por escribirnos! 

Ante todo, te pedimos disculpas por la demora en la devolución. Queremos contarte que derivamos tu consulta al equipo responsable para que la revise y pueda arreglar el problema lo antes posible. 

Saludos.

**El equipo de soporte a desarrolladores de Mercado Pago**
