### ISSUE TITLE
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by herussbol** [mercadopago/devsite-docs#563]
Blocked resources:

https://imgmp.mlstatic.com/org-img/banners/ar/medios/online/468X60.jpg

And 

https://imgmp.mlstatic.com/org-img/banners/ar/medios/online/120X600.jpg

Those resources are blocke even from :

https://www.mercadopago.com.ar/developers/es/guides/banners/online/

**Comment by MercadoPagoDevelopers** [comment]
Hola  @herussbol,
 
Te pedimos disculpas por la demora en responder. Vemos que el error ya se encuentra solucionado, lamentamos las molestias.
 
Si el error vuelve a suceder, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos ayudarte cuantos antes.

Saludos, 
El equipo de desarrolladores de Mercado Pago
