### ISSUE TITLE
Status dos Pedidos ficam voltando para "Processando" sozinho

### ISSUE THREAD

**Issue by osnipassos** [mercadopago/devsite-docs#566]
Todos os pedidos depois de concluídos voltam para o status processando
https://wordpress.org/support/topic/status-dos-pedidos-ficam-voltando-para-processando-sozinho/

**Comment by MercadoPagoDevelopers** [comment]
Olá @osnipassos,

Te pedimos desculpas pela demora em responder. Para poder te ajudar com sua dúvida, por favor contate nosso [canal de suporte](https://www.mercadopago.com.br/developers/pt/support/) para que possamos te responder o quanto antes.

Lembre-se de que este canal é para relatar problemas com a documentação de qualquer um de nossos produtos, mas não para relatar problemas com os produtos.

Atenciosamente,

**Equipe de desenvolvedores de Mercado Pago**
