### ISSUE TITLE
'external_resource_url' value using sandbox credentials with 'rapipago' and 'pagofacil'

### ISSUE THREAD

**Issue by herussbol** [mercadopago/devsite-docs#571]
## Context
  Testing payment with payment_type_id = "ticket" and  payment_method_id "rapipago" or "pagofacil" and sandbox credentials.

### Description
   Payment result:
   *  transaction_details -> external_resource_url  'contains a useless url.'

### Workaround
    Using production credentials returns a valid url in external_resource_url.

**Comment by MercadoPagoDevelopers** [comment]
Hola @herussbol ,

Ante todo, te pedimos disculpas por la demora en la devolución. Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos responderte cuantos antes.

Saludos, 

**El equipo de desarrolladores de Mercado Pago**
