### ISSUE TITLE
"Pagos sin CVV" no está en ningún menú pero es accesible con el link directo y/o desde busquedas de google. ¿Está disponible para usar?

### ISSUE THREAD

**Issue by empresarrollo** [mercadopago/devsite-docs#578]
La sección [Pagos sin CVV](https://www.mercadopago.com.ar/developers/es/guides/payments/subscriptions/preapproval) de la documentación [la tienen marcada como `indexable:  false`](https://github.com/mercadopago/devsite-docs/blob/development/guides/payments/subscriptions/preapproval.es.md), así que no aparece en la búsqueda dentro del site de `/developers`, y tampoco aparece linkeada en el menú.

**Pero SI se puede acceder directo con el link, y aparece en búsquedas de google.**

También en la [página Productos](https://www.mercadopago.com.ar/developers/es/guides/localization/products/) aparece "Pagos sin CVV" como habilitado. 

Así que la pregunta es: **¿Se puede usar esa forma de trabajo ? Si no se puede, deberian sacar esa sección completamente, o poner un mensaje explicitando que no se use.**

**Comment by DiegoMax** [comment]
Me pregunto lo mismo, puede alguien de mercadopago responder alguna vez ?

**Comment by MercadoPagoDevelopers** [comment]
Hola,

¡Gracias por escribirnos!

Esta documentación no se encuentra indexada debido a que estamos realizando tareas de mantenimiento en el producto, esta información se encuentra disponible para darle soporte a aquellos que ya contaban con el mismo, pero no recomendamos incluirlo en nuevas integraciones.

Te pedimos disculpas por las molestias ocasionadas y tendremos en cuenta tu sugerencia para mejorar nuestra documentación. 

Saludos.

**El equipo de desarrolladores de Mercado Pago**

**Comment by jcarizza** [comment]
Ya terminaron de acer el mantenimiento? Hay alguna otra forma de realizar el pago tokenizando la tarjeta?
