### ISSUE TITLE
Links rotos o mal referenciados

### ISSUE THREAD

**Issue by javicaceres** [mercadopago/devsite-docs#58]
Si mobile-checkout no está disponible para Uruguay, no lo pongamos en 
http://beta.mercadopago.com.uy/developers/es/guides/payments/button/create-button/

O arreglemos http://beta.mercadopago.com.uy/developers/es/guides/payments/mobile-checkout/introduction

Lo mismo con este:
http://beta.mercadopago.com.uy/developers/es/reference/preference

**Comment by mminestrelli** [comment]
Si mobile-checkout no está disponible para Uruguay, no lo pongamos en
http://beta.mercadopago.com.uy/developers/es/guides/payments/button/create-button/
- Fixed

O arreglemos http://beta.mercadopago.com.uy/developers/es/guides/payments/mobile-checkout/introduction
- Esto está bien ya que no es una guía que deba aparecer en el país.

Lo mismo con este:
http://beta.mercadopago.com.uy/developers/es/reference/preference
- Esto no es un issue, se debe a que se está haciendo deploy del nuevo api ref.
