### ISSUE TITLE
Falha na segurança do checkout HTTPS

### ISSUE THREAD

**Issue by marcosteisant** [mercadopago/devsite-docs#584]
A imagem do Mercado Credito exibida na página do checkout nesse link aqui: http://img.mlstatic.com/org-img/MP3/API/logos/consumer_credits.gif está sem HTTPS e vem dando erro no nosso certificado de segurança, desabilitando o mesmo na nossa página de checkout por carregar uma imagem sem HTTPS de origem. Peso atenção a esse detalhe pra evitar abandono de carrinho por falta de confiança dos clientes. Nosso site: http://www.catalogadormhi.com

**Comment by MercadoPagoDevelopers** [comment]
Olá @marcosteisant,
 
Te pedimos desculpas pela demora em responder. Para poder te ajudar com sua dúvida, por favor contate nosso [canal de suporte](https://www.mercadopago.com.br/developers/pt/support/) para que possamos te responder o quanto antes.

Atenciosamente,

**Equipe de desenvolvedores de Mercado Pago**
