### ISSUE TITLE
Missing code snipet at API -> Receiving Payments with Card section on docs website

### ISSUE THREAD

**Issue by ahsath** [mercadopago/devsite-docs#630]
## Context
Link: https://www.mercadopago.com.co/developers/en/guides/payments/api/receiving-payment-by-card/
![image](https://user-images.githubusercontent.com/37009121/75183985-9c814700-5711-11ea-80dd-ba7184aefe7e.png)

### Description
As you can see in the image above there is a missing code snipet and it is not clear what to do next, although you go to the md file https://github.com/mercadopago/devsite-docs/blob/development/guides/payments/api/receiving-payment-by-card.en.md and there it is

**Comment by lamaralmp** [comment]
Hola @ahsath, muchas gracias por tu aporte.
Es posible verlo en el archivo md pero no en el Devsite debido a un error de sintaxis en el markdown. Lo corregiremos y lo mantendremos informado.
