### ISSUE TITLE
Marketplace>Web Checkout>Introduction.es: Redacción confusa en "nota"

### ISSUE THREAD

**Issue by fdqc** [mercadopago/devsite-docs#644]
## Contexto
- Sección donde se encuentra el problema: Marketplace > Web checkout > Introducción
- Enlace: https://www.mercadopago.com.ar/developers/es/guides/marketplace/web-checkout/introduction
- Idioma: Español

### Descripción
En la documentación en español respecto del Marketplace, en su introducción la nota dice:

> La comisión de Mercado Pago será descontada de los fondos que reciba el vendedor. Primero se descuenta la comisión de Mercado Pago, y sobre el restante se descuenta la comisión del Marketplace.

Según la nota cuando un usuario realiza el pago: **Primero se descuenta la comisión de Mercado Pago** y sobre **el restante** se descuenta la comisión del Marketplace.

En la práctica **no** esta pasando esto:
Primero se descuenta la comisión del Marketplace y sobre el restante se descuenta la comisión de Mercado Pago.

Ejemplo:
![webcheckout](https://user-images.githubusercontent.com/8592318/76212346-02c49a00-61e7-11ea-9d8f-2ac28d7e71c9.png)

En el ejemplo, del total: 1.20, se descuenta la comisión del Marketplace (el 50% en este caso) 1.20 x 0.5 = **0.60**. Luego se descuenta la comisión de Mercado Pago (0.05), quedando para el vendedor **0.55** de ganancia.

De ser como detalla la documentación, debería ser:
Del total: 1.20, se descuenta la comisión de Mercado Pago (0.05), quedando 1.15, y sobre el restante descontar la comisión del Marketplace 1.15 x 0.5 = **0.575** finales para el vendedor y para el Marketplace.

**Comment by adfonseca** [comment]
Hola @fdqc. La comisión no es en porcentaje, sino por la cantidad fija colocada en el parámetro marketplace_fee. 

Entonces los pasos son:
Se calcula comisión de MP porcentual sobre el total y luego se resta
el monto de comisión de mp y de marketplace_fee.
