### ISSUE TITLE
no img src para modulos en /plugins

### ISSUE THREAD

**Issue by javicaceres** [mercadopago/devsite-docs#66]
funciona bien el link pero no tienen imagen.
Si no tenemos las imagenes podemos poner que sea solo texto con el nombre del modulo. Pero en blanco queda mal 😬 
![screen shot 2017-11-21 at 3 17 56 pm](https://user-images.githubusercontent.com/32305374/33089395-38cbdfa8-cecf-11e7-8931-9a0433ccb2ea.png)

**Comment by marcelohama** [comment]
Hola. Hice una aceso a nuestra página beta, y mi parece todo Ok con este punto:
http://beta.mercadopago.com.ar/developers/es/plugins

Es posible que las imagenes no les aparece por teneren URLs relativas a la URL de lo site. Creo que está Ok para lo entorno de producción.
