### ISSUE TITLE
La notificacion IPN es mediante GET y no mediante POST !!!

### ISSUE THREAD

**Issue by lybce** [mercadopago/devsite-docs#674]
## Context
Include:
- Articles and sections involved (with links).
- Screenshots to serve as examples.

### Description
Write a brief summary of the problem or error found. Include all information you consider relevant: where it appears, when does the situation happens and if you have any suggestions on how to solve it.

Uds dicen:
"IPN (Instant Payment Notification) es una notificación que se envía de un servidor a otro mediante una llamada HTTP POST "
y mas adelante dan el ejemplo correcto:
"Ejemplo: Si configuraste la notification_url: https://www.yoursite.com/notifications, recibirás notificaciones de pago de esta manera: https://www.yoursite.com/notifications?topic=payment&id=123456789"

**Comment by DiegoMax** [comment]
Estas confundiendo http query params con http method me parece. Son cosas diferentes. El hecho de que tenga query params como ?foo=bar no quiere decir que NO sea POST. Saludos.

**Comment by matheustt098** [comment]
¡Tengo el mismo problema! Webhook solo devuelve los parámetros id y type

**Comment by lybce** [comment]
El ID es el número de operación que genera MP. Con la API y ese número pedís el detalle del pago y te da toda la info referente a ese número de operación.

El 25 jun. 2020 22:10, matheustt098 <notifications@github.com> escribió:

¡Tengo el mismo problema! Webhook solo devuelve los parámetros id y type

**Comment by matheustt098** [comment]
Sí, pero solo están llegando estos 2 datos, y en la documentación dice que están llegando más datos, en caso de que el pago se haya actualizado, si se pagó ... pero no recibo esta actualización solo los 2 campos

**Comment by lybce** [comment]
Pasa el link de la docu, yo te explique usando una ipn clásica a una página. Vos estás usando esta notificación o estás usando webhooks ?

El 26 jun. 2020 7:57 AM, matheustt098 <notifications@github.com> escribió:

Sí, pero solo están llegando estos 2 datos, y en la documentación dice que están llegando más datos, en caso de que el pago se haya actualizado, si se pagó ... pero no recibo esta actualización solo los 2 campos

**Comment by MercadoPagoDevelopers** [comment]
Hola lybce,

¡Gracias por escribirnos!

Actualmente el envio de nuestras notificaciones de pago se realiza mediante el método POST como te indicó Diego. En dicho caso, desde Mercado Pago envianos un payload que podrás validar en nuestra documentación.
 
Por último, para poder aclarar esta situación, los datos que se envían en el payload deberás utilizarlos para realizar un GET a nuestras APIs para obtener información, ya sea sobre un pago o una orden. 

Te dejamos un ejemplo de como deberás realizar el GET para la busqueda de un pago: 
curl -G -X GET \
-H ""accept: application/json"" \
""https://api.mercadopago.com/v1/payments/<payment_id>"" \
-d ""access_token=ACCESS_TOKEN"" \
-d ""status=approved"" \
-d ""offset=0"" \
-d ""limit=10""`

Te pedimos disculpas por las molestias ocasionadas. Ante cualquier duda sobre el funcionamiento, recuerda que puedes contactarnos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos ayudarte.

Saludos,
El equipo de desarrolladores de Mercado Pago
