### ISSUE TITLE
Sofisticaci[on de

### ISSUE THREAD

**Issue by Kiboecontor** [mercadopago/devsite-docs#681]
## Context
Include:
- Articles and sections involved (with links).
- Screenshots to serve as examples.

### Description
Write a brief summary of the problem or error found. Include all information you consider relevant: where it appears, when does the situation happens and if you have any suggestions on how to solve it.

**Comment by Kiboecontor** [comment]
He encontrado un error en sus sistema informático. Paso a explicar de manera textual.
Me refiero a que sus plataformas no sean de uso al crimen organizado. Este error se desarrolla cuando un criminal tiene datos de la tarjeta de otra persona y utiliza  MercadoPago para rellenar los datos y extraer el efectivo. En este caso cabe destacar que se trata grupos funcionales al crimen organizado y para esto se hacen uso del "Testaferro" que pueden ser, sin saberlo, algunos de sus usuarios. Explico: un testaferro es una persona o entidad jurídica que sirve como depositante o depositario de un valor bancario y del cual hace de prestador del nombre y firma a su "consciente" responsabilidad; el testaferro, por su parte, puede o no saber de que irrumpe en un delito: es el "préstamo" de la identidad bancaria para transacciones.
El error no se halla en el código sino en la funcionalidad de la red MercadoPago. Por mi parte me tome el trabajo de idealizar varias soluciones a este problema.

1. Que exista un botón de pausa de transacciones:
2. Bloquear a personas para que no puedan realizar depósitos a mi cuenta:
3. Mensajes y avisos; a donde figure la responsabilidad al recibir un deposito y otro al enviar un deposito (con la opción de recordar siempre y ignorar la próxima vez):

PD: El cuidado y proteccion de sus usuarios deben de correr por su parte. Atentamente J.

**Comment by MercadoPagoDevelopers** [comment]
Hola Kiboecontor,

Antes que nada, te pedimos disculpas por la demora en responder y te agradecemos la sugerencia que nos envías.

Como mencionas, no se trata de un error en nuestra documentación sino al funcionamiento de nuestros productos.
En base a esto, para poder tomar esta sugerencia, por favor contáctanos desde nuestra [Ayuda](https://www.mercadopago.com.ar/ayuda).

Saludos, 
El equipo de soporte a desarrolladores de Mercado Pago.
