### ISSUE TITLE
Credenciales Integración Checkout MercadoPago

### ISSUE THREAD

**Issue by sebasira** [mercadopago/devsite-docs#683]
## Context
https://www.mercadopago.com.ar/developers/es/guides/payments/web-payment-checkout/integration/

### Description

En la sección de Agregar las Credenciales:
> 1.2 Agrega las credenciales para habilitar el uso de la SDK de Mercado Pago:

Dice que la forma de hacerlo es (segun el lenguaje) seteando el `ACCESS_TOKEN`
```
setAccessToken('PROD_ACCESS_TOKEN');
```

Pero en el README de **dx-java** dice que podemos usar el `ACCESS_TOKEN` para integración **Custom Checkout** y el `CLIENT_ID` y `CLIENT_SECRET` para **Web Checkout**. Creo que deberían agregarlo en la documentación porque es confuso sino, y dejan de lado el **Web Checkout**

**Comment by MercadoPagoDevelopers** [comment]
Hola Sebas,
 
Te pedimos disculpas por la demora en responder. 

Vemos que el error ya se encuentra solucionado, lamentamos las molestias. 

Si el error vuelve a suceder, por favor contáctanos desde nuestro canal de soporte para que podamos ayudarte cuantos antes.

Saludos.

**El equipo de soporte a desarrolladores de Mercado Pago**
