### ISSUE TITLE
How to specify the redirect scheme as modal?

### ISSUE THREAD

**Issue by a-ssassi-n** [mercadopago/devsite-docs#687]
In this page:
https://www.mercadopago.com.mx/developers/es/guides/payments/web-payment-checkout/customizations/

It is mentioned that we can have a modal scheme, but it's not specified how to enable modal checkout?

I am struggling to find that in the documentation.

**Comment by MercadoPagoDevelopers** [comment]
Hola,

Te pedimos disculpas por la demora en responder. 

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro canal de [soporte](https://www.mercadopago.com.ar/developers/en/support/) para que podamos responderte cuanto antes.

Saludos

**El equipo de soporte a desarrolladores de Mercado Pago**
