### ISSUE TITLE
Promise is not defined in IE11

### ISSUE THREAD

**Issue by mano290** [mercadopago/devsite-docs#692]
### Description

Hello guys, the library JS ([link](https://secure.mlstatic.com/sdk/javascript/v1/mercadopago.js)) to generate token of credit card don't have Polyfill to Promise on IE11

The payment its working, but after some time the IE11 show alert that page not working correctly...
 
## Context
- https://www.mercadopago.com.br/developers/pt/guides/payments/api/receiving-payment-by-card/#bookmark_capture_os_dados_de_cart%C3%A3o

![Capturar](https://user-images.githubusercontent.com/13751782/80224884-b8756c00-8620-11ea-99b3-dffbf085e10a.PNG)

![Capturar2](https://user-images.githubusercontent.com/13751782/80224894-bb705c80-8620-11ea-9ac6-8429b77025d6.PNG)

**Comment by MercadoPagoDevelopers** [comment]
Hola,

Te pedimos disculpas por la demora en responder. 

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro canal de [soporte](https://www.mercadopago.com.ar/developers/en/support/) para que podamos responderte cuantos antes.

Saludos

**El equipo de soporte a desarrolladores de Mercado Pago**
