### ISSUE TITLE
Error Gramatical en el plugin Mercado Pago en Woocommerce

### ISSUE THREAD

**Issue by alanfernandezb** [mercadopago/devsite-docs#703]
## Context
Include:
- Articles and sections involved (with links).
- Screenshots to serve as examples.
![MercadoPagoplugin](https://user-images.githubusercontent.com/64939908/81247697-49b0ef00-8fe0-11ea-9154-3cb5831471cb.jpg)

### Description
En el checkout de Mercado Pago en Woocommerce, en idioma Español, el combo de pagar en CUOTAS tiene un error ortográfico, dice **Seleccione el número de COTAS**, y debería decir CUOTAS. Pueden revisarlo en el checkout de la página www.enoloxica.com
Como sugerencia adicional, el pago en cuotas debería poder activarse o desactivarse desde el panel de Ajustes de Woocommerce por el administrador de la web, y no ser una opcion Default del plugin.

**Comment by MercadoPagoDevelopers** [comment]
Hola Alan,
 
Te pedimos disculpas por la demora en responder. 

Vemos que el error ya se encuentra solucionado, lamentamos las molestias. 

Si el error vuelve a suceder, por favor contáctanos desde nuestro canal de [soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos ayudarte cuantos antes.

Saludos.

**El equipo de soporte a desarrolladores de Mercado Pago**
