### ISSUE TITLE
Iconos link pago no se visualizan

### ISSUE THREAD

**Issue by MCalasso** [mercadopago/devsite-docs#711]
Al momento de generar el link de pago, no se visualizan los iconos para poder compartir el mismo mediante mail, whats app, etc.
Adjunto captura.
![Screenshot_2020-05-12-19-13-26-104_com android chrome](https://user-images.githubusercontent.com/61189882/81812703-e271ce00-94fc-11ea-90cf-38850d4e3622.jpg)

**Comment by MercadoPagoDevelopers** [comment]
Hola,

Te pedimos disculpas por la demora en responder. 

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro canal de [soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos responderte cuantos antes.

Saludos.

**El equipo de soporte a desarrolladores de Mercado Pago.**
