### ISSUE TITLE
No puedo hacer un split de pago. No encuentro solución al error!! AYUDA POR FAVOR

### ISSUE THREAD

**Issue by brianluciano** [mercadopago/devsite-docs#731]
Sigo todos los pasos que indica la documentación de mercado pago para generar un marketplace, luego genero usuarios de prueba y los utilizo como vendedor , los vinculo al marketplace de manera exitosa a través de sus user_id. Pero en el ultimo paso no logro tener éxito. El error que me muestra es el siguiente : 
{"error":"not_found","message":"Get Card Info not found","status":404,"cause":[{}]}
 
![image](https://user-images.githubusercontent.com/66273102/83442607-d05dbe00-a41e-11ea-9670-e8dcbdafa5b3.png)
![image](https://user-images.githubusercontent.com/66273102/83442645-e3708e00-a41e-11ea-8ca9-dd90c57da654.png)

en la ruta envio el access_token de la aplicacion que creé, los colectors son correctos y el token de tarjeta lo genere con la sdk de mercadopago usando los formularios de front end de mercado pago y las tarjetas de prueba de mercadopago. No se que esta sucediendo aca!!. Agradeceria algo de ayuda!

**Comment by sergio457** [comment]
Hola como estas? yo me volvi loco tratando de saber que era , hasta que , me di cuenta que era el sandbox , usa las de produccion , ya no te va a salir eso, eso si te va a salir pago rechazado , y ahora tengo ese problema las pagos quedan en veremos , si a vos te funciona , avisá por favor

**Comment by brianluciano** [comment]
Hola Buen dia!! Gracias por tu respuesta! hasta ahora no he encontrado que alguien haya podido o este en este tema! vos quedaste en ese paso? porque si no puedo probar los pagos aprobados no puedo probar el circuito completo. ! Vos decís que pruebe con las credenciales de producción ? y sigo con las tarjetas de prueba de mercadopago? Gracias!!!

**Comment by brianluciano** [comment]
Efectivamente tenias razon sergio! decime que pasos estas haciendo y te digo con que probe yo para que me apruebe el pago. 

![image](https://user-images.githubusercontent.com/66273102/83873173-a8fe3e00-a709-11ea-9b53-971201451ce0.png)

**Comment by sergio457** [comment]
q bueno q te funciono jeje , yo termine deduciendo q era el sandbox , y me funciono estuve casi dia y medio jaja hasta q me di cuenta , pero cada vez q intenté pasarle los datos , me daba rejected y en detalle rejected other reason , vos como hiciste para que te de approved ?

**Comment by brianluciano** [comment]
Te paso un ejemplo mas completo que lo saque de github
Pasos anteriores para aclarar
1) Cree 4 usuarios de prueba (con un usuario ingrese y cree la aplicacion y la configure como dice la doc de mercadopago, 2 usuarios de test use como vendedores y los vincule al marketplace(tmb funciono) una vez que los vinculas te da como resultado algo asi en cada vinculacion de los vendedores :

Respuesta :(Usariamos el user_id en el pago)
{
"access_token":"TEST-8315220229880134-060115-451bf80bffd4d96cfd0a3b22759b88dc-577620779",
"token_type":"bearer",
"expires_in":15552000,
"scope":"offline_access read write",
"user_id":577620779, (VENDEDOR 1)
"refresh_token":"TG-5ed51feac7143400061fd201-577620779",
"public_key":"TEST-d604f17e-9d5e-49d7-a95b-7a8dbdbd181c",
"live_mode":false}

del ultimo usuario solo use su direccion de correo y lo agregue en el advanced_payment

Una vez que tuve el marketplace con los vendedores asociados, para el pago con tarjeta use el formulario que te recomienda mercadopago uses para obtener los datos de tarjeta de manera segura (Es un html con javascript) La clave en este formulario es como dijo @sergio457 usar las credenciales privadas!!porque sandbox no funca. (En front end usas la public key de produccion y en backend usas el access token de producción.(Ambos de la aplicación)

![image](https://user-images.githubusercontent.com/66273102/83877111-58d6aa00-a710-11ea-85b9-4000b9a4da7b.png)


La tarjeta de crédito de prueba que use es la visa en la documentación :

Numero de tarjeta de prueba : 4170 0688 1010 8020 , cvv: 123, fecha de vencimiento 11/25, en el formulario ingrese mes: 11 año :2025. dni con 8 digitos cualquiera.

con el token de la tajeta que te da tu formulario + access token de produccion de tu aplicacion
podes probar con algo como esto.

{
	"application_id": "XXXXXXXX", // tu aplication_id
            "payments": [
                {
                "payment_method_id": "visa",  //o master o amex,...
                "payment_type_id": "credit_card",  // credit_card, debit_card , ticket/
                "token": "XXXXXX", //tu token de tarjeta devuelto por tu fgormulario
                "date_of_expiration": "2025-11-22T21:52:49.000-04:00",
                "transaction_amount": 400.15, //monto total de la operacion
                "installments": 1,
                "processing_mode": "aggregator",
                "description": "Service charge",
                "capture": true,
                "external_reference": "externalRef123",
                "statement_descriptor": "WWW.MktSplitterMLBTEST.COM.BR"
                }
            ],
            "disbursements": [
                {
                "amount": 200.15,  
                "external_reference": "8",
                "collector_id": "xxxxxx", //aca va tu user_id (vvendedor 1)
                "application_fee": 20.0,
                "money_release_days": 30,
                "additional_info": {
                    "items": [
                    {
                        "id": "item-ID-1234",
                        "title": "Title of what you are paying for",
                        "picture_url": "https://www.mercadopago.com/logomp3.gif",
                        "description": "Item description",
                        "category_id": "art",
                        "quantity": 1,
                        "unit_price": 200.15
                    }
                    ],
                    "shipments": {
                    "receiver_address": {
                        "zip_code": "5700",
                        "street_name": "Street",
                        "street_number": 123,
                        "floor": 4,
                        "apartment": "C"
                    }
                    }
                }
                },
                {
                "amount": 200,
                "external_reference": "5",
                "collector_id": "xxxxxx", //aca va tu user_id (vvendedor 2) //repetis esto dependiendo la can de vendedores que tengas
                "application_fee": 30.0,
                "money_release_days": 30,
                "additional_info": {
                    "items": [
                    {
                        "id": "item-ID-1234",
                        "title": "Title of what you are paying for",
                        "picture_url": "https://www.mercadopago.com/logomp3.gif",
                        "description": "Item description",
                        "category_id": "art",
                        "quantity": 2,
                        "unit_price": 100
                    }
                    ],
                    "shipments": {
                    "receiver_address": {
                        "zip_code": "5700",
                        "street_name": "Street",
                        "street_number": 123,
                        "floor": 4,
                        "apartment": "C"
                    }
                    }
                }
                }
            ],
            "payer": {
                "email": "test_user_51960066@testuser.com" //use este correo de usuario cliente
            },
            "external_reference": "1",
            "description": "asdasdas",
            "binary_mode": false,
            "metadata": {},
            "additional_info": {
                "items": [
                {
                    "id": "item-ID-1234",
                    "title": "Title of what you are paying for",
                    "picture_url": "https://www.mercadopago.com/logomp3.gif",
                    "description": "Item description",
                    "category_id": "art",
                    "quantity": 1,
                    "unit_price": 100
                }
                ],
                "shipments": {
                "receiver_address": {
                    "zip_code": "5700",
                    "street_name": "Street",
                    "street_number": 123,
                    "floor": 4,
                    "apartment": "C"
                }
                }
            }
            
            
}

Espero sirva de ayuda!!!

**Comment by sergio457** [comment]
Muchas Gracias , si la mayoria de lo que mencionas lo hice , pero al momento de lanzar el post me devuelve ese error , tenes un correo donde te pueda contactar ?

**Comment by brianluciano** [comment]
comasbrian@hotmail.com

**Comment by MercadoPagoDevelopers** [comment]
Hola,

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro canal de [soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos responderte cuantos antes.

Saludos.

**El equipo de soporte a desarrolladores de Mercado Pago**

**Comment by mtazzioli** [comment]
Hola! cómo están??
Estuve leyendo porque estamos teniendo el mismo problema. El tema que no puedo probar local porque no tengo certificado ssl y en consecuencia no puedo usar las credenciales de producción. 
Le encontraron alguna vuelta??

Muchísimas gracias!!!

**Comment by sergio457** [comment]
nosotros la unica que le encontramos , fue cambiar las de sandox a
produccion probadas desde postman pero aun asi el pago es rechazado o paso
a revision

**Comment by mtazzioli** [comment]
Bueno Sergio.
Tengo un caso de soporte creado en MP la semana pasada por esto mismo. Si me dan una solución les aviso!

Muchas gracias Sergio!
________________________________
De: sergio457 <notifications@github.com>
Enviado: domingo, 12 de julio de 2020 22:58
Para: mercadopago/devsite-docs <devsite-docs@noreply.github.com>
Cc: M Tazzioli <marcetazzioli@hotmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [mercadopago/devsite-docs] No puedo hacer un split de pago. No encuentro solución al error!! AYUDA POR FAVOR (#731)


nosotros la unica que le encontramos , fue cambiar las de sandox a
produccion probadas desde postman pero aun asi el pago es rechazado o paso
a revision

**Comment by fordiego44** [comment]
Gracias por la info, acabo de hacer lo mismo, hice todos los pasos tal como explico  @brianluciano pero cuando paso todo a produccion me sale el siguiente error: 

{"error":"bad_request","message":"marketplace is required.","status":400,"cause":[{"code":400011,"description":"marketplace is required.","data":null}]}

Tambien coloque el publick key en el front end. 
Esto es mi api con Curl  :

`$tuCurl = curl_init();
        curl_setopt($tuCurl, CURLOPT_URL, "https://api.mercadopago.com/v1/advanced_payments?access_token= MI ACCESS TOKEN DE LA APLICACION");
              $headers = array(
                  'Content-Type:  application/json',
                  'Accept: application/json',
              );

        curl_setopt($tuCurl, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($tuCurl, CURLOPT_POST, true);
		
		 
        $EMAIL = $request->email;
        $TOKEN = $request->token;
		$PAYMENT_METHOD_ID = $request->payment_method_id;
        $TRANSACTION_AMOUNT = $request->transaction_amount;
		$INSTALLMENTS = $request->installments;
	 

              $parametros =
                   array( 
                       "payer"   =>
                           array(
                               "email" => $EMAIL
                           ),
                       "payments" => array(
                           array(
                               "payment_method_id"     => $PAYMENT_METHOD_ID,
                               "payment_type_id"       => "credit_card",
                               "token" => $TOKEN,
                               "transaction_amount"     => $TRANSACTION_AMOUNT,
                               "installments"       => $INSTALLMENTS,
                               "processing_mode" => "aggregator"
                           )),
                       "disbursements" => array(
                           array(
                               "amount"     => 50,
                               "external_reference" => "ref-collector-1",
                               "collector_id" => ID DEL VENDEDOR 1,
                               "application_fee"     => 10,
                               "money_release_days"   => 30
                           ),
                           array(
                               "amount"     => 50,
                               "external_reference" => "ref-collector-1",
                               "collector_id" => ID DEL VENDEDOR 2,
                               "application_fee"     => 10,
                               "money_release_days"   => 30
                           )
                           ),
                       "external_reference"      => "ref-transaction"

                   );


        curl_setopt($tuCurl, CURLOPT_POSTFIELDS, json_encode($parametros));`

**Comment by GrupoDO** [comment]
Han tenido respuesta de MercadoPago? Yo escribí al soporte porque tengo este mismo problema y otro en el cual el formulario html que tokeniza la tarjeta dice que la tarjeta soporta captura diferida, pero al hacer el Payment dice que no lo soporta :S 
Ninguno de los soportes han sido respondidos ni hay forma de ver el status o si han sido asignados los cados. Bastante decepcionante la atención de MP.

@MercadoPagoDevelopers
