### ISSUE TITLE
ERROR EN EL CALCULO DE LA COMISION EN LA COMPRA EN WOOCOMERCE

### ISSUE THREAD

**Issue by rodogaby85** [mercadopago/devsite-docs#736]
la version del plugin de MercadoPago para woocomerce 4.2.1 tiene un error al hacer el calculo de la comision y luego cobrar en su plataforma. Al generar un cerrito y luego elegir forma de envio, el cual se cobra un cargo extra de acuerdo a la opcion elegida por el cliente , mercadopago hace el calculo de la comision sobre el subtotal y no sobre el total de la compra. Adjunto imagenes para que lo vean. 
[https://selfish.com.ar/wp-content/uploads/2020/06/error2.png](url)
[https://selfish.com.ar/wp-content/uploads/2020/06/error-1.png](url)

**Comment by andreszs** [comment]
No se nada sobre la comision, pero las **URL** de las imagenes que pusiste no llevan a las mismas. 
Las arreglo:

[https://selfish.com.ar/wp-content/uploads/2020/06/error2.png](https://selfish.com.ar/wp-content/uploads/2020/06/error2.png)
[https://selfish.com.ar/wp-content/uploads/2020/06/error-1.png](https://selfish.com.ar/wp-content/uploads/2020/06/error-1.png)

**Comment by pabal1708** [comment]
Hola @rodogaby85, Como estas? 

Te informamos que el canal correcto para este tipo de consultas es mediante soporte en https://www.mercadopago.com.ar/developers.

Que tengas buena tarde.


Saludos
