### ISSUE TITLE
SUGESTÃO...

### ISSUE THREAD

**Issue by zMaximus007** [mercadopago/devsite-docs#739]
Olha sinceramente tanto no mercado Pago quanto no mercado Livre não gostei nem um pouco dessa verificação de dois passos... os métodos sugeridos são muito unilaterais... seria melhor emviar um email com código direto pro email cadastrado... não é sempre que vou estar com meu celular... dai quero faser algo em 1 dos  2 mercado pago ou mercado livre e sou impedido porque requer uma verificação que eu tenho q estar com meu celular em mãos...sinceramente reveja isso confirmação por email com código também é seguro e bem mais pratico de **executar...******

**Comment by juones** [comment]
Olá zMaximus007.

Para esse tipo de ocorrência, sugerimos entrar em contato com nosso atendimento através do menu "AJUDA" do seu painel Mercado Pago.
