### ISSUE TITLE
El código de error 130 no está en la documentación.

### ISSUE THREAD

**Issue by cbdavide** [mercadopago/devsite-docs#745]
Hola, he recibido un par de veces este error en la creación de un _Customer_:
```
{  
    "message":"invalid parameters ",
    "error":"bad_request",
    "status":400,
    "cause": [ 
        {
            "code":"130",
            "description":"Invalid customer data"
        }
    ]
}
```
Pero no logro encontrar qué significa el código 130 en la documentación.

**Comment by MercadoPagoDevelopers** [comment]
Hola cbdavide,

Te pedimos disculpas por la demora en responder. 

Verificamos que este error no se encuentra documentado, tal como nos lo indicas, por lo que le enviaremos esta solicitud al equipo correspondiente para que pueda agregarlo en nuestra documentación a la brevedad.

Si aún necesitas ayuda para resolver el error, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos responderte cuanto antes.

Saludos, 
El equipo de soporte a desarrolladores de Mercado Pago.
