### ISSUE TITLE
La versión mínima de PHP para implementar la versión mas reciente del SDK es 7.1 no 5.6

### ISSUE THREAD

**Issue by danidoble** [mercadopago/devsite-docs#746]
## Problema
En la documentacion del SDK aparece que la version minima de PHP es 5.6 pero genera error

### Descripcion
El error que aparece al incluir el SDK con la version de PHP 7.0 es: 
Fatal error: Uncaught TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::registerFile() must be an instance of Doctrine\Common\Annotations\void, none returned in /home/myUser/domains/myDomain.com/public_html/go/app/includes/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php:75 Stack trace: #0 /home/myUser/domains/myDomain.com/public_html/go/app/includes/vendor/mercadopago/dx-php/src/MercadoPago/MetaDataReader.php(27): Doctrine\Common\Annotations\AnnotationRegistry::registerFile('/home/myUser...') #1 /home/myUser/domains/myDomain.com/public_html/go/app/includes/vendor/mercadopago/dx-php/src/MercadoPago/Manager.php(42): MercadoPago\MetaDataReader->__construct() #2 /home/myUser/domains/myDomain.com/public_html/go/app/includes/vendor/mercadopago/dx-php/src/MercadoPago/SDK.php(34): MercadoPago\Manager->__construct(Object(MercadoPago\RestClient), Object(MercadoPago\Config)) #3 /home/myUser/domains/myDomain.com/public_html/go/app/includes/vendor/ in /home/myUser/domains/myDomain.com/public_html/go/app/includes/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 75

### Solucion
Al cambiarla por la version 7.1 funciona bien.
Recomiendo que al ejecutar el comando de composer incluyan la version que es compatible con php 5.6, 7.0, etc.

**Comment by MercadoPagoDevelopers** [comment]
Hola Danidoble,

Te pedimos disculpas por la demora en responder. 

Te agradecemos la sugerencia para nuestra documentación y a la brevedad aclararemos este punto. 

Como mencionas, para este caso es necesario que utilices otra versión de SDK. En base a esto, te compartimos la SDK específica para las versiones de PHP menores a 7.  Podrás encontrar esta información [aquí](https://github.com/mercadopago/dx-php). 

Desde ya te pedimos disculpas por los inconvenientes que esta situación pudo generarte. 

Saludos,
El equipo de soporte a desarrolladores de Mercado Pago
