### ISSUE TITLE
Webhook dont sending informations

### ISSUE THREAD

**Issue by matheustt098** [mercadopago/devsite-docs#763]
## Context
Include:
- Articles and sections involved (with links).
https://www.mercadopago.com.br/developers/en/guides/notifications/webhooks/
- Screenshots to serve as examples.

The post method sent by the Mercado Pago Webhook just contains this information, not the complete information that has on the documentation page. The text bellow is the output of the code:
```
protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException { 
			
			
			if(request.getParameter("type") != null) {
				String type = request.getParameter("type");
				String payment_id = request.getParameter("data.id");
				
				String action = request.getParameter("action");
				
				
				System.out.println("RECEIVED INFORMATION FROM MERCADO PAGO");
				System.out.println("QUERY STING -> " + request.getQueryString());
				System.out.println("TYPE -> " + type);
				System.out.println("PAYMENT ID -> " + payment_id);
				System.out.println("ACTION -> " + action);
				System.out.println();
				
				response.setStatus(200);
				
			}
			
			
		}
```

Jun 26 03:00:30 vps-330bea9f server: QUERY STING -> data.id=27315566&type=payment
Jun 26 03:00:30 vps-330bea9f server: TYPE -> payment
Jun 26 03:00:30 vps-330bea9f server: PAYMENT ID -> 27315566
Jun 26 03:00:30 vps-330bea9f server: ACTION -> null

### Description
Write a brief summary of the problem or error found. Include all information you consider relevant: where it appears, when does the situation happens and if you have any suggestions on how to solve it.

When making a payment with the api the webhook notification don't send all the fields it is supposed to send, just 2 fields, the ID of the payment, and the type.

**Comment by MercadoPagoDevelopers** [comment]
Hola matheustt098,

Te pedimos disculpas por la demora en responder. 

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos responderte cuantos antes.

Saludos.
El equipo de soporte a desarrolladores de Mercado Pago
