### ISSUE TITLE
Update Visa test card

### ISSUE THREAD

**Issue by o-alquimista** [mercadopago/devsite-docs#772]
### Description
The Visa test card currently in the [documentation](https://www.mercadopago.com.br/developers/en/guides/payments/api/testing#bookmark_test_cards) _(4170 0688 1010 8020)_ is not working. It's always rejected with `cc_rejected_other_reason` no matter what, while the other two cards (Mastercard and American Express) are working as expected.

I have contacted support and they asked me to try this card:
```
4235 6477 2802 5682
```

It works, so I'm suggesting that we update the documentation with this new card.

**Comment by MercadoPagoDevelopers** [comment]
Hola o-alquimista, 

Antes que nada les pedimos disculpas por las demoras en la devolución desde nuestro lado y te agradecemos la colaboración.

Queremos contarte que el error mencionado con la tarjeta Visa terminada en 8020 se ha identificado y se está trabajando para corregir el mismo. Por el momento, la tarjeta seguirá disponible, y en caso de que pasado algunos días no podamos solucionar el inconveniente, modificaremos la tarjeta por la que nos envías.

Saludos.
El equipo de desarrolladores de Mercado Pago.
