### ISSUE TITLE
mercadopago.js tiene typings para usar dentro de ionic con typescript?

### ISSUE THREAD

**Issue by moises-alphacode** [mercadopago/devsite-docs#787]
Hay alguna alternativa para el sdk de js? estoy usando ionic con typescript

**Comment by MercadoPagoDevelopers** [comment]
Hola,moises-alphacode

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro canal de soporte para que podamos responderte cuantos antes. Recuerda que este canal se encuentra destinado a errores en nuestra documentación.

Saludos,
El equipo de soporte a desarrolladores de Mercado Pago

**Comment by cold-briu** [comment]
Types porfavorrrr. En el core tienen hasta el merge request con los types y no los han subido. 
Trátanos con cariño, Mercadopago
