### ISSUE TITLE
Códigos de Node.js faltantes

### ISSUE THREAD

**Issue by FedeHauque** [mercadopago/devsite-docs#789]
## Context
Include:
[Autorización y captura de pagos](https://www.mercadopago.com.ar/developers/es/guides/payments/api/other-features/)

### Description

Los códigos de Node.JS correspondientes a la captura, captura parcial y cancelación de una autorización están incompletos.

En los tres casos se incluye el siguiente texto

> var mercadopago = require('mercadopago');
> mercadopago.configurations.setAccessToken(config.access_token);

Pero no se incluye ninguna llamada a ningún método que capture, capture parcialmente o cancele una autorización.

**Comment by MercadoPagoDevelopers** [comment]
Hola @FedeHauque 

Verificamos que efectivamente nuestra documentación se encuentrava incorrecta, por lo que la arreglamos sumando los snippets faltantes.
Gracias por el feedback y te pedimos disculpas por los inconvenientes que esta situación pudo generarte.

Saludos,
El equipo de soporte a desarrolladores de Mercado Pago
