### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by JuanCaDev** [mercadopago/devsite-docs#858]
Documentación para trabajar con mercadopago separando el backend del frontend

**Comment by MercadoPagoDevelopers** [comment]
Hola @JuanCaDev 

Gracias por la sugerencia. Aplicamos este concepto (Client-side / Server-side) en algunas documentaciones, y la idea es seguir repitiéndolo para las demás.

Saludos,
El equipo de soporte para desarrolladores de Mercado Pago
