### ISSUE TITLE
Idea: api reference for Mercadopago.js

### ISSUE THREAD

**Issue by cold-briu** [mercadopago/devsite-docs#866]
I'm working on https://www.mercadopago.com.co/developers/es/guides/online-payments/checkout-api/receiving-payment-by-card/ 
it would be useful to have api reference for Mercadopago.js, things just as` window.Mercadopago.createToken` are complete magic and drops many questions behind: What's expecting? Where's calling? What's the reference for Mercadopago object?

**Comment by MercadoPagoDevelopers** [comment]
Hi @cold-briu 

Thanks for your sugestion. We will send to the responsible team. We are working on this documentation right now and we will have updates soon.

Best regards,
Mercado Pago developer support team
