### ISSUE TITLE
Advance Pagament Example Problem 

### ISSUE THREAD

**Issue by FelipoAntonoff** [mercadopago/devsite-docs#870]
Hi.

Possible problem with the article example: https://www.mercadopago.com.br/developers/pt/guides/online-payments/marketplace/advanced-payments/receive-split-payments/

We use the same example Json from the article, with a Valid Marketplace and Seller application and is giving the error:
```json
{
    "error": "not_found",
    "message": "Get Card Info not found",
    "status": 404,
    "cause": [
        {}
    ]
}
```

**Json used in the call**

```json
{
  "payer": {
    "email": "test_user_29952@testuser.com"
    },  
  "payments": [
    {
      "payment_method_id": "visa",
      "payment_type_id": "credit_card",
      "token": "979696d600bf088e6a6113f5fdf12b",
      "transaction_amount": 1000,
      "installments": 1,
      "processing_mode": "aggregator"
    }
  ],
  "disbursements": [
    {
      "amount": 1000,
      "external_reference": "ref-collector-1",
      "collector_id": 150450,
      "application_fee": 100,
      "money_release_days": 30
    }
  ],
  "external_reference": "ref-transaction"
}
```

**Json based on the example:**
```json
{
  "payer": {
    "email": "test@user.com"
  },  
  "payments": [
    {
      "payment_method_id": "visa",
      "payment_type_id": "credit_card",
      "token": "jhuyt786r5yhfcgjvhkuoy7t86r75erdfhcgv",
      "transaction_amount": 1000,
      "installments": 1,
      "processing_mode": "aggregator"
    }
  ],
  "disbursements": [
    {
      "amount": 200,
      "external_reference": "ref-collector-1",
      "collector_id": 44444444,
      "application_fee": 20,
      "money_release_days": 30
    },
    {
      "amount": 800,
      "external_reference": "ref-collector-2",
      "collector_id": 55555555,
      "application_fee": 80,
      "money_release_days": 30
    }
  ],
  "external_reference": "ref-transaction"
}
```

They could check on this possible error in the documentation or help with what may be missing.

We also did a test in the Transparent Checkout mode and took it normally, the Card token is generated in the Front correctly, just does not take Advance Payments.

I changed some data so as not to make certain information public.

Sincerely, Felipo Antonoff.

**Comment by GrupoDO** [comment]
Same problem here!

@luciagonzalez-mercadolibre @mercadopagodevelopers

**Comment by luciagonzalez-mercadolibre** [comment]
Hola, buenos días

No entendí el motivo del mail, si podrían explicarme buenisimo.

Gracias!

**Comment by GrupoDO** [comment]
Hola Lucia

El problema es que seguimos la documentacion de MercadoPago para integrar los advanced payments para pagos con split pero el servicio devuelve un error.

Te adjunto lo configurado (segun consta en la documentacion del PHP SDK):

{
  "payer": {
    "email": "test@user.com"
  },
  "payments": [
    {
      "payment_method_id": "'.$_POST['paymentMethodId'].'",
      "payment_type_id": "credit_card",
      "token": "'.$_POST['token'].'",
      "transaction_amount": 10000,

      "installments": 1,
      "statement_descriptor": "Compra ABC-123-456",

"processing_mode": "aggregator",

	"capture": false
    }
  ],
  "disbursements": [
    {
      "amount": 10000,
      "external_reference": "Reserva",
      "collector_id": 651063595,
      "application_fee": 20,
      "money_release_days": 30
    }
  ],
  "external_reference": "prueba"
}

Y la respuesta del SDK es:
{
    "error": "not_found",
    "message": "Get Card Info not found",
    "status": 404,
    "cause": [
        {}
    ]
}

Y en la documentación no aparece referencia a ese error para ver de qué se trata o cómo poder corregirlo.

Saludos!

**Comment by luciagonzalez-mercadolibre** [comment]
Desde Reporting damos soporte a otra parte del devsite:
https://www.mercadopago.com.ar/developers/es/guides/manage-account/reports/general-considerations/reconciliation-reports/


Tendrían que escribirle al equipo de Advance Payments.

Saludos

**Comment by GrupoDO** [comment]
Hola Lucia

Entiendo. Tenés algún correo del equipo de Advanced Payments? Estoy con 
una fecha de entrega cercana y no creo llegar. Gracias!


Saludos

**Comment by luciagonzalez-mercadolibre** [comment]
Por slack encontre a betina.mamani@mercadolibre.com o
matias.marciotte@mercadolibre.com

**Comment by GrupoDO** [comment]
Muchas gracias!

**Comment by MercadoPagoDevelopers** [comment]
Hola,

Te pedimos disculpas por la demora en responder.

Te indicamos que el error se puede presentar por dos situaciones:

**1**. Estás usando credenciales de prueba para realizar las pruebas. Recuerda que para probar nuestro flujo de split de pagos deberás utilizar las credenciales productivas de tu usuario de prueba.
**2.** La Publick Key utilizada para generar el token de la tarjeta, no coincide con el Access Token utilizado en el request. Puede ser porque son de distintas cuentas o de distinto tipo; como por ejemplo, una productiva y otra de prueba.

Si continúas con inconvenientes, por favor, contáctanos desde nuestro canal de [soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos ayudarte lo antes posible.

Saludos,

**El equipo de soporte a desarrolladores de Mercado Pago**

**Comment by FelipoAntonoff** [comment]
Hola, logramos resolver usando Marketplace/Aplicación en producción y los vendedores también.

En resumen, la Tarjeta de Pagos Anticipados solo toma nuestras pruebas en Producción.

Ya Boleto o Transparente Checkout con Split retoman el Sandbox normalmente.

Gracias por la ayuda.
