### ISSUE TITLE
Intereses

### ISSUE THREAD

**Issue by gregorlp** [mercadopago/devsite-docs#884]
Hola, hay planes de incorporar tazas de intereses para los pagos en cuotas?

**Comment by MercadoPagoDevelopers** [comment]
Hola,

las cuotas tienen intereses que se pueden cobrar al vendedor o comprador según la configuración que elijas en [tu panel](https://www.mercadopago.com.br/business).
Cargos adicionales por cuota pueden ser administrados directamente por su aplicación, antes de enviar la solicitud de pago a Mercado Pago.

Para más detalles por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos responderte cuantos antes. Recuerda que este canal se encuentra destinado a errores en nuestra documentación.

Saludos,
El equipo de soporte a desarrolladores de Mercado Pago
