### ISSUE TITLE
Captura diferida no funciona en AdvancedPayments

### ISSUE THREAD

**Issue by GrupoDO** [mercadopago/devsite-docs#885]
Estoy intentando integrar el marketplace usando la API de checkout, específicamente el método AdvancedPayments.

Segun la documentación en [este link](https://www.mercadopago.cl/developers/es/guides/online-payments/marketplace/advanced-payments/capture-advanced-payment) se puede hacer una autorizacion previa en la tarjeta y luego realizar la captura de los fondos.

Pero en la documentación donde se indica cómo crear un [Advanced Payment](https://www.mercadopago.cl/developers/es/guides/online-payments/marketplace/advanced-payments/receive-split-payments) no indica dónde enviar el atributo"capture:false". Así que experimenté. Si lo envío dentro del nodo Payment, no toma efecto. Los pagos son siempre capturados en el momento. Si lo envio en el nodo padre de Payment, toma efecto pero devuelve un error indicando "Error post payments in v1 Deferred capture not supported" Sin embargo al momento de consultar el medio de pago desde el formulario HTML que tokeniza la tarjeta, MercadoPago responde "deferred_capture:supported". Entonces... soporta o no soporta captura diferida? Es un error? Cómo probar correctamente?. la documentación es poco clara.

@mercadopagodevelopers

**Comment by MercadoPagoDevelopers** [comment]
Hola, @GrupoDO 

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos responderte cuantos antes. Recuerda que este canal se encuentra destinado a errores en nuestra documentación.

Saludos,
El equipo de soporte a desarrolladores de Mercado Pago
