### ISSUE TITLE
Cómo definir que el marketplace absorbe el costo de uso de MercadoPago

### ISSUE THREAD

**Issue by GrupoDO** [mercadopago/devsite-docs#886]
Según la documentación de [AdvancedPayments](https://www.mercadopago.cl/developers/es/guides/online-payments/marketplace/advanced-payments/introduction) se puede elegir quién asume el costo de uso de MercadoPago (textual "Se puede configurar quién paga la comisión de Mercado Pago"). Sin embargo no indica en ninguna parte cómo hacerlo. Qué parámetro enviar o dónde configurarlo desde algún panel de control si es que ese es el modo de hacerlo.

En mi proyecto necesito que sea el marketplace quien asuma el costo de uso de MP, descontándose el mismo del monto que toma como comisión de la venta y que el vendedor reciba el importe íntegro una vez descontada la comision del marketplace.

@mercadopagodevelopers

**Comment by MercadoPagoDevelopers** [comment]
Hola @GrupoDO ,

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos responderte cuantos antes.

Verificamos que efectivamente nuestra documentación se encuentra incompleta, por lo que le enviaremos esta solicitud al equipo correspondiente para que pueda modificar la documentación a la brevedad.
Desde ya te pedimos disculpas por los inconvenientes que esta situación pudo generarte.

Saludos,
El equipo de soporte a desarrolladores de Mercado Pago
