### ISSUE TITLE
El link "Create Discount" no funciona

### ISSUE THREAD

**Issue by ffacal** [mercadopago/devsite-docs#887]
El link de pago que figura en la página (https://www.mercadopago.com.ar/developers/en/guides/online-payments/checkout-api/discount-campaigns) no funciona: https://www.mercadopago.com.ar/campaigns/create

**Comment by MercadoPagoDevelopers** [comment]
Hola @ffacal ,

Verificamos que efectivamente nuestra documentación se encuentra incorrecta, por lo que le enviaremos esta solicitud al equipo correspondiente para que pueda modificar la documentación a la brevedad.
Desde ya te pedimos disculpas por los inconvenientes que esta situación pudo generarte.

Saludos,
El equipo de soporte a desarrolladores de Mercado Pago
