### ISSUE TITLE
Exception Message: Notice: Undefined property: Cart::$customer_secure_key

### ISSUE THREAD

**Issue by gregorlp** [mercadopago/devsite-docs#889]
Hola estoy teniendo esta excepción, alguna recomendación?, estuve viendo los requerimientos del plugin. Y el prestashop que tenemos tiene base de datos mariadb, puede esto tener relación ?
Desde ya muchas gracias
Cualquier ayuda es bienvenida

Saludos!!

**Comment by MercadoPagoDevelopers** [comment]
Hola, @gregorlp 

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos responderte cuantos antes. Recuerda que este canal se encuentra destinado a errores en nuestra documentación.

Saludos,
El equipo de soporte a desarrolladores de Mercado Pago
