### ISSUE TITLE
Android sdk 3.7.2. Error 400 Invalid Location

### ISSUE THREAD

**Issue by juanpicuervo** [mercadopago/devsite-docs#89]
IM trying to implement card token according the docs in github and in this [link](https://www.mercadopago.com.ar/developers/en/solutions/payments/custom-checkout/charge-with-creditcard/android/) and its always returning 400 invalid location on the response. Im using testing credit cards that are in mp website. Can you check if everything is correct in the sandbox API?

**Comment by joelibaceta** [comment]
Thanks for your report 👍 , please, write to our support team:  developers@mercadopago.com. The issues here should be related to the new developers site.
