### ISSUE TITLE
marketplace_fee en suscripciones

### ISSUE THREAD

**Issue by dcatanzaro** [mercadopago/devsite-docs#892]
Buenas.

Quería saber si se puede usar el marketplace_fee en las suscripciones y si no es así si se piensa agregar en algún momento.

Muchas gracias.
Saludos.

**Comment by MercadoPagoDevelopers** [comment]
Hola, @dcatanzaro 

Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/) para que podamos responderte cuantos antes. Recuerda que este canal se encuentra destinado a errores en nuestra documentación.

Saludos,
El equipo de soporte a desarrolladores de Mercado Pago
