### ISSUE TITLE
Token = "YOUR_CARD_TOKEN" le falta la "," en el json del ejemplo

### ISSUE THREAD

**Issue by hugocarregno** [mercadopago/devsite-docs#900]
Token = "YOUR_CARD_TOKEN" le falta la "," en el json del ejemplo linea 11

**Comment by MercadoPagoDevelopers** [comment]
Hola @hugocarregno 

Verificamos que efectivamente nuestra documentación se encuentra incorrecta, por lo que le enviaremos esta solicitud al equipo correspondiente para que pueda modificar la documentación a la brevedad.

Desde ya te pedimos disculpas por los inconvenientes que esta situación pudo generarte.

Saludos,
**El equipo de soporte a desarrolladores de Mercado Pago**
