### ISSUE TITLE
el enlace al formulario de soporte no funciona

### ISSUE THREAD

**Issue by hugocarregno** [mercadopago/devsite-docs#901]
https://www.mercadopago.com/mla/support

**Comment by MercadoPagoDevelopers** [comment]
Hola @hugocarregno 

Gracias por el feedback. El enlace correcto a nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support/) es este.

Verificamos que efectivamente nuestra documentación se encuentra incorrecta, por lo que le enviaremos esta solicitud al equipo correspondiente para que pueda modificar la documentación a la brevedad.

Desde ya te pedimos disculpas por los inconvenientes que esta situación pudo generarte.

Saludos,
**El equipo de soporte a desarrolladores de Mercado Pago**
