### ISSUE TITLE
error sintaxis codigo ejemplo

### ISSUE THREAD

**Issue by hugocarregno** [mercadopago/devsite-docs#902]
https://www.mercadopago.com.ar/developers/es/guides/online-payments/checkout-pro/integration#editor_1602793896
linea 20 de csharp se agrego " de mas

**Comment by MercadoPagoDevelopers** [comment]
Hola @hugocarregno 

Verificamos que efectivamente nuestra documentación se encuentra incompleta, por lo que le enviaremos esta solicitud al equipo correspondiente para que pueda modificar la documentación a la brevedad.
Desde ya te pedimos disculpas por los inconvenientes que esta situación pudo generarte.

Saludos,
**El equipo de soporte a desarrolladores de Mercado Pago**
