### ISSUE TITLE
Bug no Gateway do mercado livre e mercado pago 

### ISSUE THREAD

**Issue by anubis792** [mercadopago/devsite-docs#911]
Achei um bug na plataforma do mercado livre, que na minha opinião é bem catastrófico, Pois ele permite o usuário a ter mercadorias de graça. E eu quero ajudar a  resolver esse bug.
Para mais informações entre em contato: anubis792@hotmail.com

**Comment by MercadoPagoDevelopers** [comment]
Olá @anubis792 

Obrigado pelo contato. Para poder seguir, por favor nos contate através do nosso [canal de suporte](https://www.mercadopago.com.br/developers/pt/support/) para que possamos dar sequência o quanto antes.

**Mercado Pago Developers**
