### ISSUE TITLE
Enlace roto en payment-retry.en.md y payment-retry.es.md

### ISSUE THREAD

**Issue by alejandro088** [mercadopago/devsite-docs#926]
### Description
Enlace roto en payment-retry.en.md y payment-retry.es.md. Deberia ir **advanced** en lugar de **advenced**.

**Comment by MercadoPagoDevelopers** [comment]
Hola @alejandro088 

Verificamos que efectivamente nuestra documentación se encuentra incorrecta. Gracias por su contribución en el #925 
Desde ya te pedimos disculpas por los inconvenientes que esta situación pudo generarte.

Saludos,
**El equipo de soporte a desarrolladores de Mercado Pago**
