### ISSUE TITLE
Add example for "other-features.md" with saved cards

### ISSUE THREAD

**Issue by santiago-ley** [mercadopago/devsite-docs#956]
Is this supported? I'm getting error "Deferred capture not supported" with the following code.
I suggest adding an example if it's supported, or stating that's not supported otherwise (or in which countries it's supported if that matters).

```
  MercadoPago\SDK::setAccessToken("ENV_ACCESS_TOKEN");

  $payment = new MercadoPago\Payment();

  $payment->transaction_amount = 20;
  $payment->token = "TOKEN";
  $payment->description = "descripcion";
  $payment->installments = 1;
  $payment->payment_method_id = "master";
  $payment->payer = array(
    "email" => "EMAIL",
    "type" => "customer",
    "id" => "CUSTOMER_ID"
  );

  $payment->capture=false;

  $payment->save();
```

**Comment by felipe0528** [comment]
Same problem here but with .Net

**Comment by MercadoPagoDevelopers** [comment]
Hi @santiago-ley 

Thanks for reporting. We are checking with the responsible team and will send you a response as soon as possible.

Regards,
**The Mercado Pago development team.**

**Comment by Leleocastro** [comment]
Some solution? Or why this error is occurring.

**Comment by biaguerreiromeli** [comment]
@santiago-ley could you provide more details regarding the doc in which you are missing the code example?

**Comment by biaguerreiromeli** [comment]
Hola, @santiago-ley  👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a la problemática inherente a la plataforma y sus integraciones. Solo está destinado a almacenar código y documentaciones públicos. 

**Tenemos un canal oficial de soporte súper preparado para solucionar rápidamente tu caso.** 
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support

¡Muchas gracias por su contacto!
