### ISSUE TITLE
paymentsplit error5000

### ISSUE THREAD

**Issue by halvarado2401** [mercadopago/devsite-docs#972]
## Context
Estoy intentnado crear un payment split , ya hice todo el proceso de crear el collector_id  correctamente ( al inicio tuve los problemas de este hilo https://github.com/mercadopago/devsite-docs/issues/731 ) y de usar las credenciales de produccion, el card token lo estoy generando desde el mismo sitio con el plugin de prestashop que ya recibe el token como  tal, pero cuando ejecuto el el curl para el pago obtengo la siguiente respuesta
 
{
    "error": "internal_server_error",
    "message": "internal_server_error",
    "status": 500
}
![Screenshot 2020-12-14 103209](https://user-images.githubusercontent.com/75997514/102100666-b6525e80-3df7-11eb-9867-92b10aa4daa1.png)

**Comment by MercadoPagoDevelopers** [comment]
Hola @halvarado2401 

Te pedimos disculpas por la demora en responder. Para poder ayudarte con la consulta, por favor contáctanos desde nuestro [canal de soporte](https://www.mercadopago.com.ar/developers/es/support) para que podamos responderte cuantos antes.

Saludos, 
**El equipo de soporte a desarrolladores de Mercado Pago"**
