### ISSUE TITLE
Mensagem resposta não está correta na documentação

### ISSUE THREAD

**Issue by lucioaguiar** [mercadopago/devsite-docs#975]
Na documentação está dizendo que o código 224 é referente a falta do código de segurança:

![Screenshot_20201215_005135](https://user-images.githubusercontent.com/70476123/102168884-d291e200-3e6f-11eb-8233-09f700976752.png)

mas quando emito esse erro ele apresenta o código: 3031 que não está presente na lista de erros.

![Screenshot_20201215_004907](https://user-images.githubusercontent.com/70476123/102168858-c4dc5c80-3e6f-11eb-94ed-07abe5456fd1.png)

Gostaria de saber onde posso encontrar os código reais dos erros, pois estou realizando testes na minha aplicação.
Estou usando mercadopago/dx-php versão 2.2.1

**Comment by MercadoPagoDevelopers** [comment]
Olá @lucioaguiar 

Obrigado pelo reporte. Constatamos que a informação está incorreta no Devsite.
No momento a lista complete de códigos de erro não está disponível, toda a seção de Referências de API está sendo refatorada e em breve todas as APIs estarão atualizadas.

Atenciosamente,
**Equipe de suporte a desenvolvedores de Mercado Pago**

**Comment by lucioaguiar** [comment]
Obrigado.
