### ISSUE TITLE
Gema Ruby y documentación no coinciden

### ISSUE THREAD

**Issue by abelorian** [mercadopago/devsite-docs#983]
En la integración de Checkout API con Ruby, hay referencias que no existen en la gema oficial:

```
MercadoPago::SDK
```
```
MercadoPago::Payment
```

![image](https://user-images.githubusercontent.com/544935/102818237-f7c2ab00-43af-11eb-991f-1b90c8472292.png)

https://www.mercadopago.com.co/developers/es/guides/online-payments/checkout-api/other-payment-ways

**Comment by MercadoPagoDevelopers** [comment]
Hola @abelorian ,

Te pedimos disculpas por la demora en responder. Gracias por informarnos. Estamos consultando con el equipo responsable y le enviaremos una respuesta lo antes posible.

Saludos, 
**El equipo de soporte a desarrolladores de Mercado Pago**

**Comment by biaguerreiromeli** [comment]
Hola, @abelorian  👋 

Le pedimos disculpas por la demora y por el inconveniente en su fluxo de trabajo.

Aun siendo abierto, este espacio no pretende servir como herramienta de soporte a la problemática inherente a la plataforma y sus integraciones. Solo está destinado a almacenar código y documentaciones públicos. 

**Tenemos un canal oficial de soporte súper preparado para solucionar rápidamente tu caso.** 
Por eso, si el error persiste, recopile toda la información y accede aquí para compartir conosco el problema: https://www.mercadopago.com/developers/es/support

¡Muchas gracias por su contacto!
